HOST = "127.0.0.1"
PORT = 25000

# === STANDARDIZED MAP SETTINGS ===
STANDARD_MAP_WIDTH = 1024
STANDARD_MAP_HEIGHT = 1024
STANDARD_MAP_Y = 256

# === ACTION SETTINGS (NOW CONTINUOUS TARGETS) ===
NOOP_ACTION = "NOOP"

# Sampling settings for continuous target selection
NUM_RANDOM_TARGETS = 30
TARGET_PADDING = 50

# Command persistence settings
MIN_STEPS_BETWEEN_COMMANDS = 3
COMMAND_DISTANCE_EPS = 50
OVERRIDE_SCORE_THRESHOLD = 10.0
CANCEL_COMMAND_PENALTY = 2.0

# === EPISODIC TRAINING SETTINGS ===
EPISODE_TIMEOUT_SECONDS = 60
MASS_REACH_RADIUS = 100
MASS_FINAL_APPROACH_RADIUS = 140
MASS_DESTINATION_SWAP_THRESHOLD = 0.10
MAX_SEGMENT_STEPS = 300

# Potential-based move rewards
POTENTIAL_DISTANCE_SCALE = 0.1
POTENTIAL_DIRECTION_SCALE = 0.05
HEIGHT_JUMP_TOLERANCE = 15.0
HEIGHT_JUMP_PENALTY_SCALE = 0.2
IMMEDIATE_DAMAGE_PENALTY_SCALE = 2.0
PATH_DANGER_PENALTY_SCALE = 10.0
PATH_DANGER_MIN_HIT_PENALTY = 2.0

# Segment (mass-spot) rewards
SEGMENT_BASE_REWARD = 200.0
FAILURE_BASE_PENALTY = 150.0
SEGMENT_TIME_PENALTY = 0.5
SEGMENT_DISTANCE_PENALTY = 0.1
SEGMENT_DAMAGE_PENALTY = 1.0
HEIGHT_DISTANCE_FACTOR = 0.2

# Number of action features for the potential field
NUM_ACTION_FEATURES = 4

# Terrain sampling for path-based penalties
PATH_TERRAIN_WEIGHT = 0.25
PATH_SPIKE_THRESHOLD = 5.0
PATH_SAMPLE_COUNT = 6
TERRAIN_WAYPOINT_COUNT = 8
TERRAIN_WAYPOINT_SEARCH_RADIUS = 300

# Maximum traversable slope (height delta between adjacent cells in normalized space)
# Corresponds to 0.412 slope in real space assuming 4:1 aspect ratio (1024:256)
MAX_TRAVERSABLE_SLOPE = 0.412

# Persistent cache for map pathfinding precomputations
MAP_CACHE_DIR = "cache/map_fields"
MAP_CACHE_VERSION = 1

# === ENCODER SETTINGS ===
SELF_FEATURES_SIZE = 6
SELF_EMBED_SIZE = 16
MASS_FEATURES_SIZE = 3
MASS_EMBED_SIZE = 8
MAP_FEATURES_SIZE = 6
MAP_EMBED_SIZE = 16
UNIT_FEATURES_SIZE = 3
ENEMY_FEATURES_SIZE = 4
FRIENDLY_EMBED_SIZE = 16
ENEMY_EMBED_SIZE = 16

# === LSTM SETTINGS ===
LSTM_HIDDEN_SIZE = 64
LSTM_NUM_LAYERS = 1

# === MODEL VISUALIZATION SETTINGS ===
ENABLE_MODEL_GRAPH_LOG = True

# === EPOCH DRIFT SETTINGS ===
td_cap = 5.0

# === OUTPUT WEIGHT CONSTRAINTS ===
ENFORCE_DISTANCE_REDUCTION_NONNEG = True
DISTANCE_REDUCTION_INDEX = 0

FEATURE_NAMES = [
    "distance_reduction",
    #"boundary_proximity",
    "move_magnitude",
    #"terrain_steepness",
    "is_noop",
    #"height_change",
    "danger_zone",
]
