/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

#include "CppTestAI.h"


#include "ExternalAI/Interface/AISEvents.h"
#include "ExternalAI/Interface/AISCommands.h"

// generated by the C++ Wrapper scripts
#include "OOAICallback.h"
#include "OptionValues.h"
#include "SkirmishAI.h"
#include "Unit.h"
#include "UnitDef.h"
#include "MoveData.h"
#include "DataDirs.h"
#include "Game.h"
#include "Map.h"
#include "Cheats.h"
#include "Command.h"

#include <string>
#include <memory>
#include <fstream>
#include <sstream>
#include <cstring>
#include <cctype>
#include <cstdlib>
#include <string_view>

cpptestai::CCppTestAI::CCppTestAI(springai::OOAICallback* callback):
		callback(callback),
		skirmishAIId(callback != NULL ? callback->GetSkirmishAIId() : -1),
		spawnRosterIndex(0)
{
	// LoadSpawnRoster();
}

cpptestai::CCppTestAI::~CCppTestAI() {}

namespace {

	std::vector<std::string> ParseSpawnRoster(const std::string& roster)
	{

		std::vector<std::string> units;
		std::string current;
		std::stringstream ss(roster);
		char delim = ','; // Default delimiter
		std::string item;

		while (std::getline(ss, item, delim)) {
			units.push_back(item);
		}

		return units;
	}

}

std::vector<springai::Unit*> friendlyUnits = std::vector<springai::Unit*>();
std::vector<springai::AIFloat3> massSpots = std::vector<springai::AIFloat3>();
bool massSpotsInitialized = false;
std::vector<springai::AIFloat3> spawnPositions = std::vector<springai::AIFloat3>();
std::vector<std::string> spawnRoster;

bool initialBuilding = false;
bool preppedSpawn = false;
bool faction = false;
int dangerSpawn = 10;
int seconds = 25;

static inline std::string IntToString(int i, const std::string& format = "%i")
{
	char buf[64];
	SNPRINTF(buf, sizeof(buf), format.c_str(), i);
	return std::string(buf);
}

static inline std::string FloatToString(float f, const std::string& format = "%.3f")
{
	char buf[64];
	SNPRINTF(buf, sizeof(buf), format.c_str(), f);
	return std::string(buf);
}

int cpptestai::CCppTestAI::HandleEvent(int topic, const void* data) {

	switch (topic) {
		case EVENT_UPDATE: {
			const std::unique_ptr<springai::Game> game(callback->GetGame());
			std::unique_ptr<springai::Cheats> cheats(callback->GetCheats());
			cheats->SetEnabled(true);
			const std::unique_ptr<springai::Map> map(callback->GetMap());
			struct SUpdateEvent* evt = (struct SUpdateEvent*) data;
			int frame = evt->frame;
			
			
			if(frame%60 == 0){

				seconds++;
				
				auto* metalResource = callback->GetResourceByName("Metal");
				std::vector<springai::Unit*> Units = callback->GetFriendlyUnits();

				game->SendTextMessage("/say Update", 0);

				if(!massSpotsInitialized || massSpots.empty()){
					massSpots = map->GetResourceMapSpotsPositions(metalResource);
					massSpotsInitialized = !massSpots.empty();

					// Load the map spawn positions
					// 1022.78094,116.272949,893.809998 South
					// 1027.48999,106.518555,534.420959 Middle
					// 1025.77295,108.015747,130.194153 Top
					// spawnPositions.push_back(springai::AIFloat3(1022.78094f, 116.272949f, 893.809998f));
					// spawnPositions.push_back(springai::AIFloat3(1027.48999f, 106.518555f, 534.420959f));
					// spawnPositions.push_back(springai::AIFloat3(1025.77295f, 108.015747f, 130.194153f));

					// Missile
					// "armrock": {
					//     "dps": 41,
					//     "range": 475
					// },
					// "armjanus": {
					//     "dps": 88,
					//     "range": 380
					// },
					// "armsam": {
					//     "dps": 26,
					//     "range": 550
					// },
					spawnRoster = {
						"armrock",
						"armjanus",
						"armsam"
					};

					// projectile
					// 	"armstump": {
					//     "dps": 83,
					//     "range": 350
					// },
					// "armcroc": {
					//     "dps": 141,
					//     "range": 480
					// },
					// "corraid": {
					//     "dps": 83,
					//     "range": 350
					// },
					spawnRoster.push_back("armstump");
					spawnRoster.push_back("armcroc");
					spawnRoster.push_back("corraid");

					// hitscan
					// "armflash": {
					// 	"dps": 90,
					// 	"range": 260
					// },
					// "corgator": {
					// 	"dps": 93.75,
					// 	"range": 230
					// },
					// "corsumo": {
					// 	"dps": 503,
					// 	"range": 650
					// },
					// "armwar": {
					// 	"dps": 183,
					// 	"range": 325
					// },
					spawnRoster.push_back("armflash");
					spawnRoster.push_back("corgator");
					spawnRoster.push_back("corsumo");
					spawnRoster.push_back("armwar");

					game->SendTextMessage("/say Mass spots initialized", 0);
				}
				else if(massSpotsInitialized && (seconds % 30 == 0)){ // incorrect use of seconds, it technically is every 2
					// Choose a random mass point pair (spawn and destination to loop between)
					if (massSpots.size() >= 2 && !spawnRoster.empty()) {
						int spawnIdx = rand() % massSpots.size();
						int destIdx = rand() % massSpots.size();
						while (spawnIdx == destIdx) {
							destIdx = rand() % massSpots.size();
						}
						
						springai::AIFloat3 spawnPos = massSpots[spawnIdx];
						springai::AIFloat3 destPos = massSpots[destIdx];
						spawnPos.y = map->GetElevationAt(spawnPos.x, spawnPos.z);
						destPos.y = map->GetElevationAt(destPos.x, destPos.z);

						// Choose a random unit to spawn from the roster
						int unitIdx = rand() % spawnRoster.size();
						std::string unitName = spawnRoster[unitIdx];
						springai::UnitDef* spawnDef = callback->GetUnitDefByName(unitName.c_str());
						
						if (spawnDef) {
							int spawnedUnitId = cheats->GiveMeUnit(spawnDef, spawnPos);
							
							// provide unit a patrol route between the chosen mass points
							std::vector<springai::Unit*> checkUnits = callback->GetFriendlyUnits();
							for (springai::Unit* u : checkUnits) {
								if (u->GetUnitId() == spawnedUnitId) {
									u->PatrolTo(destPos);
									break;
								}
							}
						}
					}
				}
				else{
					try{
						for(springai::Unit* unit : Units){
							const char* unitDefName = unit->GetDef()->GetName();
							game->SendTextMessage(("/say Processing unit with ID: " + IntToString(unit->GetUnitId()) + " and name: " + (unitDefName != nullptr ? unitDefName : "<null>")).c_str(), 0);
							if(unitDefName != nullptr && (std::strcmp(unitDefName, "armcom") == 0 || std::strcmp(unitDefName, "corcom") == 0)){
								continue;
							}
						}
						
					}
					catch(...){
						game->SendTextMessage("/say Error occurred in UPDATE", 0);
					}
				}
			}

		}
		default: {
			break;
		}
	}

	// signal: everything went OK
	return 0;
}
