/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

#include "CppTestAI.h"


#include "ExternalAI/Interface/AISEvents.h"
#include "ExternalAI/Interface/AISCommands.h"

// generated by the C++ Wrapper scripts
#include "OOAICallback.h"
#include "Unit.h"
#include "UnitDef.h"
#include "MoveData.h"
#include "DataDirs.h"
#include "Game.h"
#include "Map.h"
#include "Cheats.h"

#include <string>
#include <memory>
#include <fstream>
#include <string>

// for vector removal
#include <algorithm>
#include "Command.h"

cpptestai::CCppTestAI::CCppTestAI(springai::OOAICallback* callback):
		callback(callback),
		skirmishAIId(callback != NULL ? callback->GetSkirmishAIId() : -1)
		{}

cpptestai::CCppTestAI::~CCppTestAI() {}

// make the masspoint tracker

std::vector<springai::Unit*> friendlyUnits = std::vector<springai::Unit*>();
std::vector<springai::AIFloat3> massSpots = std::vector<springai::AIFloat3>();
std::vector<bool> massSpotTaken = std::vector<bool>();
bool massSpotsInitialized = false;

static inline std::string IntToString(int i, const std::string& format = "%i")
{
	char buf[64];
	SNPRINTF(buf, sizeof(buf), format.c_str(), i);
	return std::string(buf);
}

static inline std::string FloatToString(float f, const std::string& format = "%.3f")
{
	char buf[64];
	SNPRINTF(buf, sizeof(buf), format.c_str(), f);
	return std::string(buf);
}

int cpptestai::CCppTestAI::HandleEvent(int topic, const void* data) {

	switch (topic) {
		case EVENT_UNIT_CREATED: {
			
			break;
		}
		case EVENT_UPDATE: {

			struct SUpdateEvent* evt = (struct SUpdateEvent*) data;
			int frame = evt->frame;

			if(frame%120 == 0){

				const std::unique_ptr<springai::Game> game(callback->GetGame());
				if (game == nullptr) {
					break;
				}

				const std::unique_ptr<springai::Map> map(callback->GetMap());
				if (map == nullptr) {
					game->SendTextMessage("/say Map callback was null", 0);
					break;
				}

				// Get AI team id
				int myTeamId = game->GetMyTeam();

				// Grab the units position
				std::vector<springai::Unit*> Units = callback->GetFriendlyUnits();
				springai::Unit* createdUnit = Units[0];

				if (createdUnit == nullptr) {
					game->SendTextMessage("/say Created unit lookup failed", 0);
					break;
				}

				std::unique_ptr<springai::Cheats> cheats(callback->GetCheats());
				if (cheats == nullptr) {
					game->SendTextMessage("/say Cheats interface unavailable", 0);
					break;
				}

				cheats->SetEnabled(true);
				springai::UnitDef* spawnDef = callback->GetUnitDefByName("armpw");
				if (spawnDef == nullptr) {
					game->SendTextMessage("/say UnitDef armpw not found", 0);
					break;
				}

				// Spawn in a unit via cheats callback command channel
				springai::AIFloat3 spawnPos = createdUnit->GetPos();
				spawnPos.y = map->GetElevationAt(spawnPos.x, spawnPos.z);
				const int spawnedUnitId = cheats->GiveMeUnit(spawnDef, spawnPos);
				if (spawnedUnitId > 0) {
					game->SendTextMessage((std::string("/say Spawned cheat unit id: ") + IntToString(spawnedUnitId)).c_str(), 0);
				} else {
					game->SendTextMessage("/say Cheat spawn failed", 0);
				}
			}
			break;
		}
		default: {
			break;
		}
	}

	// signal: everything went OK
	return 0;
}
