/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

#include "CppTestAI.h"


#include "ExternalAI/Interface/AISEvents.h"
#include "ExternalAI/Interface/AISCommands.h"

// generated by the C++ Wrapper scripts
#include "OOAICallback.h"
#include "OptionValues.h"
#include "SkirmishAI.h"
#include "Unit.h"
#include "UnitDef.h"
#include "MoveData.h"
#include "DataDirs.h"
#include "Game.h"
#include "Map.h"
#include "Cheats.h"
#include "Command.h"

#include <string>
#include <memory>
#include <fstream>
#include <cstring>
#include <cctype>

cpptestai::CCppTestAI::CCppTestAI(springai::OOAICallback* callback):
		callback(callback),
		skirmishAIId(callback != NULL ? callback->GetSkirmishAIId() : -1),
		spawnRosterIndex(0)
{
	LoadSpawnRoster();
}

cpptestai::CCppTestAI::~CCppTestAI() {}

namespace {

std::vector<std::string> ParseSpawnRoster(const std::string& roster)
{
	std::vector<std::string> units;
	std::string current;
	for (char ch : roster) {
		const unsigned char uch = static_cast<unsigned char>(ch);
		const bool isSeparator = std::isspace(uch) || (ch == '+') || (ch == ',') || (ch == ';') || (ch == '|');
		if (isSeparator) {
			if (!current.empty()) {
				units.push_back(current);
				current.clear();
			}
			continue;
		}
		current.push_back(ch);
	}
	if (!current.empty()) {
		units.push_back(current);
	}
	return units;
}

}

void cpptestai::CCppTestAI::LoadSpawnRoster()
{
	spawnRoster.clear();
	spawnRosterIndex = 0;

	if (callback == nullptr) {
		return;
	}

	springai::SkirmishAI* skirmishAI = callback->GetSkirmishAI();
	if (skirmishAI == nullptr) {
		return;
	}

	std::unique_ptr<springai::OptionValues> options(skirmishAI->GetOptionValues());
	if (!options) {
		return;
	}

	const char* value = options->GetValueByKey("spawn_roster");
	if (value == nullptr || *value == '\0') {
		return;
	}

	spawnRoster = ParseSpawnRoster(value);
}

springai::UnitDef* cpptestai::CCppTestAI::GetSpawnUnitDef()
{
	if (callback == nullptr) {
		return nullptr;
	}

	if (!spawnRoster.empty()) {
		for (std::size_t attempts = 0; attempts < spawnRoster.size(); ++attempts) {
			const std::string& unitName = spawnRoster[spawnRosterIndex % spawnRoster.size()];
			++spawnRosterIndex;
			springai::UnitDef* spawnDef = callback->GetUnitDefByName(unitName.c_str());
			if (spawnDef != nullptr) {
				return spawnDef;
			}
		}
	}

	const int choice = rand() % 100 + 1;
	if (choice <= 10) {
		return callback->GetUnitDefByName("armcroc");
	}
	if (choice <= 70) {
		return callback->GetUnitDefByName("corthud");
	}
	return callback->GetUnitDefByName("armstump");
}

std::vector<springai::Unit*> friendlyUnits = std::vector<springai::Unit*>();
std::vector<springai::AIFloat3> massSpots = std::vector<springai::AIFloat3>();
bool massSpotsInitialized = false;
std::vector<springai::AIFloat3> spawnPositions = std::vector<springai::AIFloat3>();
std::vector<std::string> spawnRoster;

bool initialBuilding = false;
bool faction = false;
int dangerSpawn = 10;

static inline std::string IntToString(int i, const std::string& format = "%i")
{
	char buf[64];
	SNPRINTF(buf, sizeof(buf), format.c_str(), i);
	return std::string(buf);
}

static inline std::string FloatToString(float f, const std::string& format = "%.3f")
{
	char buf[64];
	SNPRINTF(buf, sizeof(buf), format.c_str(), f);
	return std::string(buf);
}

int cpptestai::CCppTestAI::HandleEvent(int topic, const void* data) {

	switch (topic) {
		case EVENT_UPDATE: {
			const std::unique_ptr<springai::Game> game(callback->GetGame());
			std::unique_ptr<springai::Cheats> cheats(callback->GetCheats());
			cheats->SetEnabled(true);
			const std::unique_ptr<springai::Map> map(callback->GetMap());
			struct SUpdateEvent* evt = (struct SUpdateEvent*) data;
			int frame = evt->frame;
			
			
			if(frame%60 == 0){
				
				auto* metalResource = callback->GetResourceByName("Metal");
				std::vector<springai::Unit*> Units = callback->GetFriendlyUnits();

				game->SendTextMessage("/say Update", 0);

				if(!massSpotsInitialized || massSpots.empty()){
					massSpots = map->GetResourceMapSpotsPositions(metalResource);
					massSpotsInitialized = !massSpots.empty();

					// Load the map spawn positions
					// 1022.78094,116.272949,893.809998 South
					// 1027.48999,106.518555,534.420959 Middle
					// 1025.77295,108.015747,130.194153 Top
					// spawnPositions.push_back(springai::AIFloat3(1022.78094f, 116.272949f, 893.809998f));
					// spawnPositions.push_back(springai::AIFloat3(1027.48999f, 106.518555f, 534.420959f));
					// spawnPositions.push_back(springai::AIFloat3(1025.77295f, 108.015747f, 130.194153f));

					// Missile
					// "armrock": {
					//     "dps": 41,
					//     "range": 475
					// },
					// "armjanus": {
					//     "dps": 88,
					//     "range": 380
					// },
					// "armsam": {
					//     "dps": 26,
					//     "range": 550
					// },

					// projectile
					// 	"armstump": {
					//     "dps": 83,
					//     "range": 350
					// },
					// "armcroc": {
					//     "dps": 141,
					//     "range": 480
					// },
					// "corraid": {
					//     "dps": 83,
					//     "range": 350
					// },

					// hitscan
					// "armflash": {
					// 	"dps": 90,
					// 	"range": 260
					// },
					// "corgator": {
					// 	"dps": 93.75,
					// 	"range": 230
					// },
					// "corsumo": {
					// 	"dps": 503,
					// 	"range": 650
					// },
					// "armwar": {
					// 	"dps": 183,
					// 	"range": 325
					// },

					spawnRoster = {
						"armwar", // Individual
						"corraid",
						"armjanus",

						"armwar", // Group
						"corraid",
						"armjanus",

						"corraid", //garenteed empty path

						"corraid", // 50/50, empty path
						"corraid", 

						"corraid", // 50/50 empty path
						"corraid", 

						"armwar", // Forced to go through one of them
						"armflash",

						"armsam", // Forced to go through one of them
						"armwar",

						"armwar", // 3 split open path
						"armflash",
						"corgator",

						"armwar", // 3 split open path
						"armflash",
						"corgator",

						"armwar", // 3 split open path
						"armflash",
						"corgator",

						"armwar", // 3 path forced to go through one of them
						"armflash",
						"corgator",

						"armwar", // 3 path forced to go through one of them
						"armflash",
						"corgator",

					};

					// 4439.2666,3.82910156,7743.22217
					spawnPositions.push_back(springai::AIFloat3(4439.2666f, 3.82910156f, 7743.22217f));
					// 5496.41504,3.76660156,7746.7832
					spawnPositions.push_back(springai::AIFloat3(5496.41504f, 3.76660156f, 7746.7832f));
					// 6541.88818,3.75439453,7746.7832
					spawnPositions.push_back(springai::AIFloat3(6541.88818f, 3.75439453f, 7746.7832f));

					// 6987.12891,3.89038086,5904.43164
					spawnPositions.push_back(springai::AIFloat3(6987.12891f, 3.89038086f, 5904.43164f));
					// 7376.90137,3.66748047,5882.91504
					spawnPositions.push_back(springai::AIFloat3(7376.90137f, 3.66748047f, 5882.91504f));
					// 7377.3125,0,5882.71533
					spawnPositions.push_back(springai::AIFloat3(7377.3125f, 0.0f, 5882.71533f));

					// 6550.01416,3.82836914,4940.09717
					spawnPositions.push_back(springai::AIFloat3(6550.01416f, 3.82836914f, 4940.09717f));

					// 7851.90039,3.90893555,3894.64307
					spawnPositions.push_back(springai::AIFloat3(7851.90039f, 3.90893555f, 3894.64307f));
					// 6589.12988,3.76123047,3903.86865
					spawnPositions.push_back(springai::AIFloat3(6589.12988f, 3.76123047f, 3903.86865f));

					// 6520.41992,3.67041016,2944.20947
					spawnPositions.push_back(springai::AIFloat3(6520.41992f, 3.67041016f, 2944.20947f));
					// 7821.92188,3.68847656,2974.8064
					spawnPositions.push_back(springai::AIFloat3(7821.92188f, 3.68847656f, 2974.8064f));

					// 6624.53174,3.64306641,2252.46948
					spawnPositions.push_back(springai::AIFloat3(6624.53174f, 3.64306641f, 2252.46948f));
					// 7870.23486,3.75634766,2237.16821
					spawnPositions.push_back(springai::AIFloat3(7870.23486f, 3.75634766f, 2237.16821f));

					// 6601.23584,3.76782227,1494.56836
					spawnPositions.push_back(springai::AIFloat3(6601.23584f, 3.76782227f, 1494.56836f));
					// 7785.21875,3.85449219,1485.37085
					spawnPositions.push_back(springai::AIFloat3(7785.21875f, 3.85449219f, 1485.37085f));

					// 5086.50098,3.73120117,1352.31982
					spawnPositions.push_back(springai::AIFloat3(5086.50098f, 3.73120117f, 1352.31982f));
					// 5096.5542,4.03442383,758.72052
					spawnPositions.push_back(springai::AIFloat3(5096.5542f, 4.03442383f, 758.72052f));
					// 5075.3208,3.73413086,122.374603
					spawnPositions.push_back(springai::AIFloat3(5075.3208f, 3.73413086f, 122.374603f));

					// 4206.58154,3.97680664,1413.63599
					spawnPositions.push_back(springai::AIFloat3(4206.58154f, 3.97680664f, 1413.63599f));
					// 4206.58154,3.97680664,730.646973
					spawnPositions.push_back(springai::AIFloat3(4206.58154f, 3.97680664f, 730.646973f));
					// 4230.98486,3.81396484,92.8037109
					spawnPositions.push_back(springai::AIFloat3(4230.98486f, 3.81396484f, 92.8037109f));

					// 3418.24048,4.27563477,1413.63599
					spawnPositions.push_back(springai::AIFloat3(3418.24048f, 4.27563477f, 1413.63599f));
					// 3418.24048,4.27563477,764.367493
					spawnPositions.push_back(springai::AIFloat3(3418.24048f, 4.27563477f, 764.367493f));
					// 3460.91724,3.7421875,108.344788
					spawnPositions.push_back(springai::AIFloat3(3460.91724f, 3.7421875f, 108.344788f));

					// 2665.07935,3.84887695,1413.63599
					spawnPositions.push_back(springai::AIFloat3(2665.07935f, 3.84887695f, 1413.63599f));
					// 2665.07935,3.84887695,764.367493
					spawnPositions.push_back(springai::AIFloat3(2665.07935f, 3.84887695f, 764.367493f));
					// 2678.07153,3.72973633,95.9953613
					spawnPositions.push_back(springai::AIFloat3(2678.07153f, 3.72973633f, 95.9953613f));

					// 1893.04651,3.86181641,1368.26782
					spawnPositions.push_back(springai::AIFloat3(1893.04651f, 3.86181641f, 1368.26782f));
					// 1893.04651,3.86181641,764.367493
					spawnPositions.push_back(springai::AIFloat3(1893.04651f, 3.86181641f, 764.367493f));
					// 1896.15869,4.04223633,89.6871338
					spawnPositions.push_back(springai::AIFloat3(1896.15869f, 4.04223633f, 89.6871338f));

					

					game->SendTextMessage("/say Mass spots/spawn roster initialized", 0);
				}
				else if(Units.size() == 1){
					game->SendTextMessage("/say Only one unit, spawning new units", 0);
					//game->SendTextMessage("/say The amount of spawnPositions is: " + IntToString(spawnPositions.size()), 0);
					game->SendTextMessage(("/say The amount of spawnPositions is: " + IntToString(spawnPositions.size())).c_str(), 0);
					
					bool split1 = false; // 7
					bool split2 = false; // 9
					bool split3 = false; // 15
					bool split4 = false; // 18
					bool split5 = false; // 21
					
					for(int i = 0; i < spawnPositions.size(); i++){
						game->SendTextMessage(("/say Spawning unit at position: " + FloatToString(spawnPositions[i].x) + ", " + FloatToString(spawnPositions[i].y) + ", " + FloatToString(spawnPositions[i].z)).c_str(), 0);

						//cheats->GiveMeUnit(callback->GetUnitDefByName("armcom"), spawnPositions[i]);
					
						// Spawn in laser unit to control
						springai::AIFloat3 spawnPos = spawnPositions[i];
						spawnPos.y = map->GetElevationAt(spawnPos.x, spawnPos.z);

						springai::UnitDef* spawnDef = callback->GetUnitDefByName(spawnRoster[i % spawnRoster.size()].c_str());
						if (spawnDef == nullptr) {
							game->SendTextMessage("/say No valid spawn unit found", 0);
							return 0;
						}

						if (i == 7 && rand() % 2 == 0) {
							split1 = true;
						} else if (i == 9 && rand() % 2 == 0) {
							split2 = true;
						} else if (i == 15 && rand() % 2 == 0) {
							split3 = true;
						} else if (i == 18 && rand() % 2 == 0) {
							split4 = true;
						} else if (i == 21 && rand() % 2 == 0) {
							split5 = true;
						}

						if (i == 8 && split1) {
							game->SendTextMessage("/say Skipping spawn at index 8 due to split1", 0);
							continue;
						} else if (i == 10 && split2) {
							game->SendTextMessage("/say Skipping spawn at index 10 due to split2", 0);
							continue;
						} else if ((i == 16 || i == 17) && split3) {
							game->SendTextMessage("/say Skipping spawn at index 16 due to split3", 0);
							split3 = false; // Reset split3 after skipping
							continue;
						} else if ((i == 19 || i == 20) && split4) {
							game->SendTextMessage("/say Skipping spawn at index 19 due to split4", 0);
							split4 = false; // Reset split4 after skipping
							continue;
						} else if ((i == 22 || i == 23) && split5) {
							game->SendTextMessage("/say Skipping spawn at index 22 due to split5", 0);
							split5 = false; // Reset split5 after skipping
							continue;
						}
						else if (i == 7 && !split1) {
							game->SendTextMessage("/say Skipping spawn at index 7 due to split1", 0);
							continue;
						} else if (i == 9 && !split2) {
							game->SendTextMessage("/say Skipping spawn at index 9 due to split2", 0);
							continue;
						} else if (i == 15 && !split3) {
							game->SendTextMessage("/say Skipping spawn at index 15 due to split3", 0);
							continue;
						} else if (i == 18 && !split4) {
							game->SendTextMessage("/say Skipping spawn at index 18 due to split4", 0);
							continue;
						} else if (i == 21 && !split5) {
							game->SendTextMessage("/say Skipping spawn at index 21 due to split5", 0);
							continue;
						}

						const int spawnedUnitId = cheats->GiveMeUnit(spawnDef, spawnPos);
						game->SendTextMessage(("/say Spawned unit with ID: " + IntToString(spawnedUnitId)).c_str(), 0);
					}
				}
				else{
					try{
						for(springai::Unit* unit : Units){
							const char* unitDefName = unit->GetDef()->GetName();
							game->SendTextMessage(("/say Processing unit with ID: " + IntToString(unit->GetUnitId()) + " and name: " + (unitDefName != nullptr ? unitDefName : "<null>")).c_str(), 0);
							if(unitDefName != nullptr && (std::strcmp(unitDefName, "armcom") == 0 || std::strcmp(unitDefName, "corcom") == 0)){
								continue;
							}
						}
						
					}
					catch(...){
						game->SendTextMessage("/say Error occurred in UPDATE", 0);
					}
				}
			}

		}
		default: {
			break;
		}
	}

	// signal: everything went OK
	return 0;
}
