/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

#include "CppTestAI.h"


#include "ExternalAI/Interface/AISEvents.h"
#include "ExternalAI/Interface/AISCommands.h"

// generated by the C++ Wrapper scripts
#include "OOAICallback.h"
#include "OptionValues.h"
#include "SkirmishAI.h"
#include "Unit.h"
#include "UnitDef.h"
#include "MoveData.h"
#include "DataDirs.h"
#include "Game.h"
#include "Map.h"
#include "Cheats.h"
#include "Command.h"

#include <string>
#include <memory>
#include <fstream>
#include <sstream>
#include <cstring>
#include <cctype>
#include <string_view>

cpptestai::CCppTestAI::CCppTestAI(springai::OOAICallback* callback):
		callback(callback),
		skirmishAIId(callback != NULL ? callback->GetSkirmishAIId() : -1),
		spawnRosterIndex(0)
{
	LoadSpawnRoster();
}

cpptestai::CCppTestAI::~CCppTestAI() {}

namespace {

static constexpr int CMD_WANT_CLOAK = 37382;

std::vector<std::string> ParseSpawnRoster(const std::string& roster)
{

	std::vector<std::string> units;
	std::string current;
	std::stringstream ss(roster);
	char delim = ','; // Default delimiter
	std::string item;

	while (std::getline(ss, item, delim)) {
        units.push_back(item);
    }

	return units;
}

}

void cpptestai::CCppTestAI::LoadSpawnRoster()
{
	spawnRoster.clear();
	spawnRosterIndex = 0;

	if (callback == nullptr) {
		return;
	}

	springai::SkirmishAI* skirmishAI = callback->GetSkirmishAI();
	if (skirmishAI == nullptr) {
		return;
	}

	std::unique_ptr<springai::OptionValues> options(skirmishAI->GetOptionValues());
	if (!options) {
		return;
	}

	const char* value = options->GetValueByKey("spawn_roster");
	if (value == nullptr || *value == '\0') {
		return;
	}

	spawnRoster = ParseSpawnRoster(value);
}

springai::UnitDef* cpptestai::CCppTestAI::GetSpawnUnitDef()
{
	if (callback == nullptr) {
		return nullptr;
	}

	if (!spawnRoster.empty()) {
		for (std::size_t attempts = 0; attempts < spawnRoster.size(); ++attempts) {
			const std::string& unitName = spawnRoster[spawnRosterIndex % spawnRoster.size()];
			++spawnRosterIndex;
			if(unitName == ""){
				return nullptr;
			}
			springai::UnitDef* spawnDef = callback->GetUnitDefByName(unitName.c_str());
			if (spawnDef != nullptr) {
				return spawnDef;
			}
		}
	}

	const int choice = rand() % 100 + 1;
	if (choice <= 10) {
		return callback->GetUnitDefByName("armcroc");
	}
	if (choice <= 70) {
		return callback->GetUnitDefByName("corthud");
	}
	return callback->GetUnitDefByName("armstump");
}

std::vector<springai::Unit*> friendlyUnits = std::vector<springai::Unit*>();
std::vector<springai::AIFloat3> massSpots = std::vector<springai::AIFloat3>();
bool massSpotsInitialized = false;
std::vector<springai::AIFloat3> spawnPositions = std::vector<springai::AIFloat3>();
std::vector<int> pendingCloakUnits = std::vector<int>();

bool initialBuilding = false;
bool preppedSpawn = false;
bool faction = false;
int dangerSpawn = 10;

static inline std::string IntToString(int i, const std::string& format = "%i")
{
	char buf[64];
	SNPRINTF(buf, sizeof(buf), format.c_str(), i);
	return std::string(buf);
}

static inline std::string FloatToString(float f, const std::string& format = "%.3f")
{
	char buf[64];
	SNPRINTF(buf, sizeof(buf), format.c_str(), f);
	return std::string(buf);
}

static bool TryCloakSpawnedUnit(springai::OOAICallback* callback, int unitId)
{
	if (callback == nullptr) {
		return false;
	}

	std::vector<springai::Unit*> units = callback->GetFriendlyUnits();
	for (springai::Unit* unit : units) {
		if (unit == nullptr || unit->GetUnitId() != unitId) {
			continue;
		}

		if (unit->IsCloaked()) {
			return true;
		}

		springai::UnitDef* unitDef = unit->GetDef();
		if (unitDef != nullptr && unitDef->IsAbleToCloak()) {
			unit->ExecuteCustomCommand(CMD_WANT_CLOAK, {1.f});
		}

		return unit->IsCloaked();
	}

	return false;
}

int cpptestai::CCppTestAI::HandleEvent(int topic, const void* data) {

	switch (topic) {
		case EVENT_UPDATE: {
			const std::unique_ptr<springai::Game> game(callback->GetGame());
			std::unique_ptr<springai::Cheats> cheats(callback->GetCheats());
			cheats->SetEnabled(true);
			const std::unique_ptr<springai::Map> map(callback->GetMap());
			struct SUpdateEvent* evt = (struct SUpdateEvent*) data;
			int frame = evt->frame;

			for (auto it = pendingCloakUnits.begin(); it != pendingCloakUnits.end(); ) {
				if (TryCloakSpawnedUnit(callback, *it)) {
					game->SendTextMessage(("/say Unit cloaked successfully: " + IntToString(*it)).c_str(), 0);
					it = pendingCloakUnits.erase(it);
				} else {
					++it;
				}
			}
			
			
			if(frame%60 == 0){
				
				auto* metalResource = callback->GetResourceByName("Metal");
				std::vector<springai::Unit*> Units = callback->GetFriendlyUnits();

				game->SendTextMessage("/say Update", 0);

				if(!massSpotsInitialized || massSpots.empty()){
					massSpots = map->GetResourceMapSpotsPositions(metalResource);
					massSpotsInitialized = !massSpots.empty();

					// Load the map spawn positions
					// 1022.78094,116.272949,893.809998 South
					// 1027.48999,106.518555,534.420959 Middle
					// 1025.77295,108.015747,130.194153 Top
					spawnPositions.push_back(springai::AIFloat3(1022.78094f, 116.272949f, 893.809998f));
					spawnPositions.push_back(springai::AIFloat3(1027.48999f, 106.518555f, 534.420959f));
					spawnPositions.push_back(springai::AIFloat3(1025.77295f, 108.015747f, 130.194153f));

					game->SendTextMessage("/say Mass spots initialized", 0);
				}
				else if(massSpotsInitialized && !massSpots.empty() && preppedSpawn == false){
					preppedSpawn = true;
					game->SendTextMessage("/say Only one unit, spawning new units", 0);
					//game->SendTextMessage("/say The amount of spawnPositions is: " + IntToString(spawnPositions.size()), 0);
					game->SendTextMessage(("/say The amount of spawnPositions is: " + IntToString(spawnPositions.size())).c_str(), 0);
						
					springai::SkirmishAI* skirmishAI = callback->GetSkirmishAI();
					std::unique_ptr<springai::OptionValues> options(skirmishAI->GetOptionValues());
					const char* value = options->GetValueByKey("spawn_roster");

					std::string stringValue = value != nullptr ? std::string(value) : std::string("<null>");

					game->SendTextMessage(("/say Spawn roster: " + stringValue).c_str(), 0);
					std::vector<std::string> spawnUnits;

					size_t r = stringValue.find(",");
					size_t lastPos = 0;
					while (r != std::string::npos) {
						std::string unitName = stringValue.substr(lastPos, r - lastPos);
						game->SendTextMessage(("/say detected unit name: " + unitName).c_str(), 0);
						spawnUnits.push_back(unitName);
						// stringValue += r + 1;
						lastPos = r + 1;
						r = stringValue.find(",", r + 1);

					}
					spawnUnits.push_back(stringValue.substr(lastPos, r - lastPos));
					game->SendTextMessage(("/say detected unit name: " + spawnUnits.back()).c_str(), 0);

					for(int i = 0; i < spawnPositions.size(); i++){
						game->SendTextMessage(("/say Spawning unit at position: " + FloatToString(spawnPositions[i].x) + ", " + FloatToString(spawnPositions[i].y) + ", " + FloatToString(spawnPositions[i].z)).c_str(), 0);

						//cheats->GiveMeUnit(callback->GetUnitDefByName("armcom"), spawnPositions[i]);
					
						// Spawn in laser unit to control
						springai::AIFloat3 spawnPos = spawnPositions[i];
						spawnPos.y = map->GetElevationAt(spawnPos.x, spawnPos.z);
						if (spawnUnits[i].empty() || spawnUnits[i] == "") {
							game->SendTextMessage("/say Empty Spot or no valid unit def", 0);
							continue;
						}
						springai::UnitDef* spawnDef = callback->GetUnitDefByName(spawnUnits[i].c_str());
						if (spawnDef == nullptr) {
							game->SendTextMessage("/say Empty Spot or no valid unit def", 0);
							
						}
						else{
							const int spawnedUnitId = cheats->GiveMeUnit(spawnDef, spawnPos);
							// Set the unit to hold position after spawn
							// GiveOrder
							std::vector<springai::Unit*> checkUnits = callback->GetFriendlyUnits();
							for (springai::Unit* u : checkUnits) {
								if (u->GetUnitId() == spawnedUnitId) {
									u->SetMoveState(0); // 0 Hold Position, 1 Maneuver, 2 Roam

									// Only ask for cloak on units that actually support it.
									springai::UnitDef* unitDef = u->GetDef();
									if (unitDef != nullptr && unitDef->IsAbleToCloak()) {
										u->ExecuteCustomCommand(CMD_WANT_CLOAK, {1.f});
										if (!u->IsCloaked()) {
											pendingCloakUnits.push_back(spawnedUnitId);
										}
									}
									break;
								}
							}

							

							//springai::Unit* unit = callback->GetUnitById(spawnedUnitId);
							// if (unit != nullptr) {
							// 	unit->SetMoveState(0); // 0 Hold Position, 1 Maneuver, 2 Roam
							// }

							game->SendTextMessage(("/say Spawned unit with ID: " + IntToString(spawnedUnitId)).c_str(), 0);
						}
					}

					
				}
				else{
					try{
						for(springai::Unit* unit : Units){
							const char* unitDefName = unit->GetDef()->GetName();
							game->SendTextMessage(("/say Processing unit with ID: " + IntToString(unit->GetUnitId()) + " and name: " + (unitDefName != nullptr ? unitDefName : "<null>")).c_str(), 0);
							if(unitDefName != nullptr && (std::strcmp(unitDefName, "armcom") == 0 || std::strcmp(unitDefName, "corcom") == 0)){
								continue;
							}
						}
						
					}
					catch(...){
						game->SendTextMessage("/say Error occurred in UPDATE", 0);
					}
				}
			}

		}
		default: {
			break;
		}
	}

	// signal: everything went OK
	return 0;
}
