/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

#ifndef _CPPTESTAI_CPPTESTAI_H
#define _CPPTESTAI_CPPTESTAI_H

#include <atomic>
#include <chrono>
#include <mutex>
#include <thread>

// generated by the C++ Wrapper scripts
#include "OOAICallback.h"

namespace cpptestai {

/**
 * This is the main C++ entry point of this AI.
 * 
 * @author	Robin Vobruba <hoijui.quaero@gmail.com>
 */
class CCppTestAI {

private:
	springai::OOAICallback* callback;
	int skirmishAIId;

	std::thread pauseWorker;
	std::atomic<bool> pauseWorkerRunning;
	std::atomic<bool> pauseWorkerStop;
	std::atomic<bool> workerTick;
	std::atomic<bool> unpauseRequested;
	std::atomic<bool> aiPausedGame;
	std::atomic<int> pauseSeconds;
	std::chrono::steady_clock::time_point pauseDeadline;
	std::mutex pauseMutex;

	void StartPauseWorker();
	void StopPauseWorker();
	void PauseWorkerLoop();
	void SetPauseForSeconds(int seconds);
	void ProcessPauseWorkerState();

public:
	CCppTestAI(springai::OOAICallback* callback);
	~CCppTestAI();

	int HandleEvent(int topic, const void* data);
}; // class CCppTestAI

} // namespace cpptestai

#endif // _CPPTESTAI_CPPTESTAI_H

