/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

#include "CppTestAI.h"


#include "ExternalAI/Interface/AISEvents.h"
#include "ExternalAI/Interface/AISCommands.h"

// generated by the C++ Wrapper scripts
#include "OOAICallback.h"
// #include "AIAICallback.h" Might be useful later but not now
#include "File.h"
#include "Unit.h"
#include "UnitDef.h"
#include "Command.h"
#include "WrappCurrentCommand.h"
#include "WrappResource.h"
#include "Game.h"
#include "Map.h"
#include "Mod.h"

#include <string>
#include <unordered_map>
#include <unordered_set>
#include <memory>
#include <chrono>
#include <thread>

// for file input/output
#include <filesystem>
#include <fstream>
#include <sstream>

#include <unistd.h>

// // for socket operations test
// extern "C" {
//   #include <winsock2.h> // Or the specific header
//   #include <ws2tcpip.h>
//   #include <afunix.h>
// }
// This doesn't work due to the nature of the compiler and I don't want to have to recode the engine
// As such, we are bound by file transfer, not terribly efficent but doable.

// #include <winsock2.h>
// #include <ws2tcpip.h>
// #pragma comment(lib, "Ws2_32.lib")
#include <asio.hpp>
using asio::ip::tcp;
#include "Networking/asioConnector.h"

// for vector removal
#include <algorithm>



cpptestai::CCppTestAI::CCppTestAI(springai::OOAICallback* callback):
		callback(callback),
		skirmishAIId(callback != NULL ? callback->GetSkirmishAIId() : -1),
		pauseWorkerRunning(false),
		pauseWorkerStop(false),
		workerTick(false),
		unpauseRequested(false),
		aiPausedGame(false),
		pauseSeconds(0),
		pauseDeadline(std::chrono::steady_clock::now())
		{}

cpptestai::CCppTestAI::~CCppTestAI() {
	StopPauseWorker();
}

void cpptestai::CCppTestAI::StartPauseWorker() {
	if (pauseWorkerRunning.load())
		return;

	pauseWorkerStop.store(false);
	pauseWorkerRunning.store(true);
	pauseWorker = std::thread(&CCppTestAI::PauseWorkerLoop, this);
}

void cpptestai::CCppTestAI::StopPauseWorker() {
	pauseWorkerStop.store(true);

	if (pauseWorker.joinable())
		pauseWorker.join();

	pauseWorkerRunning.store(false);
}

void cpptestai::CCppTestAI::PauseWorkerLoop() {
	while (!pauseWorkerStop.load()) {
		std::this_thread::sleep_for(std::chrono::milliseconds(100));
		workerTick.store(true);

		if (!aiPausedGame.load())
			continue;

		std::chrono::steady_clock::time_point deadline;
		{
			std::lock_guard<std::mutex> lock(pauseMutex);
			deadline = pauseDeadline;
		}

		if (std::chrono::steady_clock::now() >= deadline) {
			aiPausedGame.store(false);
			unpauseRequested.store(true);

			const std::unique_ptr<springai::Game> game(callback->GetGame());
			game->SetPause(false, "AI pause worker timeout reached");
		}
	}
}

void cpptestai::CCppTestAI::SetPauseForSeconds(int seconds) {
	if (seconds < 0)
		seconds = 0;

	pauseSeconds.store(seconds);
	{
		std::lock_guard<std::mutex> lock(pauseMutex);
		pauseDeadline = std::chrono::steady_clock::now() + std::chrono::seconds(seconds);
	}

	aiPausedGame.store(true);
	unpauseRequested.store(false);
}

void cpptestai::CCppTestAI::ProcessPauseWorkerState() {
	workerTick.exchange(false);

	if (unpauseRequested.exchange(false)) {
		aiPausedGame.store(false);
	}
}

struct fakeUnit {
	int id; 
	std::string name; 
	int range;
	springai::AIFloat3 pos;
	float hp;

	fakeUnit(int i, std::string n, int r, springai::AIFloat3 p, float h) : id(i), name(n), range(r), pos(p), hp(h){

	}
};

static const char* RADAR_UNKNOWN_NAME = "RADAR_UNKNOWN";

// Keep radar contacts separate from confirmed LOS contacts so uncertain
// detections do not overwrite identified enemy data.
static void UpsertFakeUnit(std::vector<fakeUnit>& units, int id, const std::string& name, int range, const springai::AIFloat3& pos, float hp) {
	auto it = std::find_if(units.begin(), units.end(), [id](const fakeUnit& u){
		return u.id == id;
	});

	if (it == units.end()) {
		units.emplace_back(id, name, range, pos, hp);
		return;
	}

	it->name = name;
	it->range = range;
	it->pos = pos;
	it->hp = hp;
}

static void EraseFakeUnitById(std::vector<fakeUnit>& units, int id) {
	units.erase(
		std::remove_if(
			units.begin(),
			units.end(),
			[id](const fakeUnit& unit) {
				return unit.id == id;
			}
		),
		units.end()
	);
}

struct importantSpot {
	springai::AIFloat3 pos;
	std::string type;
	float value;

	importantSpot(springai::AIFloat3 p, std::string t, float v) : pos(p), type(t), value(v){

	}
	importantSpot() : pos(springai::AIFloat3(0, 0, 0)), type(""), value(0){

	}
};

std::vector<springai::Unit*> friendlyUnits = std::vector<springai::Unit*>();
// std::unordered_map<springai::Unit*, springai::Unit*> builderConnections = std::unordered_map<springai::Unit*, springai::Unit*>();
std::vector<fakeUnit> knownEnemyUnits = std::vector<fakeUnit>();
std::vector<springai::Unit*> enemyUnits = std::vector<springai::Unit*>();
std::vector<fakeUnit> radarEnemyUnits = std::vector<fakeUnit>();

std::unordered_map<int, std::unordered_set<int>> buildersOf;
std::unordered_map<int, int> projectOf;
std::vector<std::pair<int, std::string>> finishedThisTurn;
std::unordered_set<int> myBuilders;
// springai::Unit* FindNanoframeForBuilder(springai::Unit* builder);

std::vector<float> mapHeights;
std::vector<float> enemyThreat;
std::vector<float> projectilePaths;

// std::string PersonalUnitsPath = "currentUnits.txt";
// std::string CommandsPath = "unitCommands.txt";
// std::string EnemyUnitsPath = "enemyUnits.txt";
// std::string KnownEnemyUnitsPath = "knownEnemyUnits.txt";

bool begin = false;

std::unique_ptr<TCPClient> connector;

bool transfer = false;

static std::string LoadStreamIntoString(std::istream& is) {
    std::ostringstream ss;
    ss << is.rdbuf();
    return ss.str();
}

static inline std::string IntToString(int i, const std::string& format = "%i")
{
	char buf[64];
	SNPRINTF(buf, sizeof(buf), format.c_str(), i);
	return std::string(buf);
}

int cpptestai::CCppTestAI::HandleEvent(int topic, const void* data) {

	// Helper to safely obtain a unit definition name without assuming
	// the unit is fully identified (radar-only contacts may not have a def).
	auto safeUnitDefName = [&](springai::Unit* unit) -> std::string {
		if (unit == nullptr)
			return std::string(RADAR_UNKNOWN_NAME);
		try {
			const std::unique_ptr<springai::UnitDef> udef(unit->GetDef());
			if (!udef)
				return std::string(RADAR_UNKNOWN_NAME);
			return udef->GetName();
		} catch (...) {
			return std::string(RADAR_UNKNOWN_NAME);
		}
	};


	switch (topic) {
		case EVENT_UNIT_CREATED: {

			// Struct: `SUnitCreatedEvent`
			// - Key fields: `int unit; int builder;`
			// - Description: A unit of this team was created (nano-frame stage).

			struct SUnitCreatedEvent* evt = (struct SUnitCreatedEvent*) data;
			int unitId = evt->unit;
			int builderId = evt->builder;
			const std::unique_ptr<springai::Game> game(callback->GetGame());

			game->SendTextMessage(("/say Unit created with ID: " + IntToString(unitId) + ", builder ID: " + IntToString(builderId)).c_str(), 0);

			if(!begin){
				friendlyUnits = callback->GetFriendlyUnits();
				begin = true;
			}
			else{
				std::vector<springai::Unit*> allUnits = callback->GetFriendlyUnits();
				for (springai::Unit* u : allUnits) {
					if (u->GetUnitId() == unitId) {
						friendlyUnits.push_back(u);
					}
					else {
						delete u; // clean up units not added to friendlyUnits to prevent memory leak
					}
				}
			}

			if (builderId > 0) {
				buildersOf[unitId].insert(builderId);
				projectOf[builderId] = unitId;
			}

			// --- NEW: Check if this new unit is itself a builder ---
			// We use GetFriendlyUnits here anyway (existing code), so piggyback on it.
			// We'll also check buildSpeed via UnitDef.
			for (springai::Unit* unit : friendlyUnits) {
				if (unit->GetUnitId() == unitId) {
					std::unique_ptr<springai::UnitDef> udef(unit->GetDef());
					if (udef && udef->GetBuildSpeed() > 0.0f) {
						myBuilders.insert(unitId);
					}
					break;
				}
			}

			std::string msgText = std::string("/say Hello Engine (from myAI), num my units is ") + IntToString(friendlyUnits.size());
			if (!friendlyUnits.empty()) {
				springai::Unit* unit = friendlyUnits[0];
				std::string unitDefName = safeUnitDefName(unit);
				msgText = msgText + ", first friendly units def name is: " + unitDefName;
			}
			
			game->SendTextMessage(msgText.c_str(), 0);

			begin = true;
			
			break;
		}
		case EVENT_UNIT_FINISHED: {
			if (!begin) {
				break;
			}
			const std::unique_ptr<springai::Game> game(callback->GetGame());
			struct SUnitFinishedEvent* evt = (struct SUnitFinishedEvent*) data;
			int unitId = evt->unit;

			buildersOf.erase(unitId);

			std::vector<springai::Unit*> Units = callback->GetFriendlyUnits();
			for(springai::Unit* unit : Units){
				if(unit->GetUnitId() == unitId){
					std::unique_ptr<springai::UnitDef> udef(unit->GetDef());
					// add to the friendly units list

					if (udef && udef->GetBuildSpeed() > 0.0f) {
						myBuilders.insert(unitId);
					}
					auto itF = std::find_if(friendlyUnits.begin(), friendlyUnits.end(), [unitId](const springai::Unit* u){
						return u->GetUnitId() == unitId;
					});
					if(itF == friendlyUnits.end()){
						friendlyUnits.push_back(unit);
					}

					std::string msgText = std::string("/say Unit finished with Name: ") + safeUnitDefName(unit) + ", ID: " + IntToString(unitId);
					const std::unique_ptr<springai::Game> game(callback->GetGame());
					game->SendTextMessage(msgText.c_str(), 0);
					finishedThisTurn.push_back({unitId, safeUnitDefName(unit)});

					break;
				}
			}

			break;
		}
		case EVENT_UNIT_DESTROYED: {
			if (!begin) {
				break;
			}
			struct SUnitDestroyedEvent* evt = (struct SUnitDestroyedEvent*) data;
			int unitId = evt->unit;

			myBuilders.erase(unitId);

			// If this unit was a builder working on something, remove it from
    		// that nanoframe's builder set
			auto projIt = projectOf.find(unitId);
			if (projIt != projectOf.end()) {
				int nanoframe = projIt->second;
				auto bofIt = buildersOf.find(nanoframe);
				if (bofIt != buildersOf.end()) {
					bofIt->second.erase(unitId);
					if (bofIt->second.empty())
						buildersOf.erase(bofIt);
				}
				projectOf.erase(projIt);
			}

			// If this unit WAS a nanoframe (cancelled or killed mid-build), erase
			// it from buildersOf and clean up all builders that pointed to it
			auto bofIt = buildersOf.find(unitId);
			if (bofIt != buildersOf.end()) {
				for (int bid : bofIt->second) {
					projectOf.erase(bid);
				}
				buildersOf.erase(bofIt);
			}

			friendlyUnits.erase(
				std::remove_if(friendlyUnits.begin(), friendlyUnits.end(),
					[unitId](springai::Unit* u){ return u->GetUnitId() == unitId; }),
				friendlyUnits.end()
			);

			break;
		}
		case EVENT_INIT: {
			StartPauseWorker();

			const std::unique_ptr<springai::Game> game(callback->GetGame());
			std::string cwd;
			// try {
			// 	cwd = std::filesystem::current_path().string();
			// } catch (const std::exception&) {
			// 	cwd = "<unknown>";
			// }
			char cwdBuf[4096];
			if (getcwd(cwdBuf, sizeof(cwdBuf)) != nullptr) {
				cwd = std::string(cwdBuf);
			} else {
				cwd = "<unknown>";
			}
			std::string msgText = std::string("/say Running from directory: ") + cwd;
			game->SendTextMessage(msgText.c_str(), 0);

			game->SendTextMessage(msgText.c_str(), 0);

			// Write out map information for external use
			std::ofstream mapInfoFile("mapInfo.txt",  std::ios::binary | std::ios::trunc);
			std::ofstream massInfoFile("massInfo.txt",  std::ios::binary | std::ios::trunc);
			std::ofstream mapHeightInfoFile("mapHeightInfo.txt",  std::ios::binary | std::ios::trunc);
			if (mapInfoFile) {
				const std::unique_ptr<springai::Map> map(callback->GetMap());

				std::string mapName = map->GetName();
				int mapWidth = map->GetWidth(); // This returns a value that gets *8 to get full rez
				int mapHeight = map->GetHeight();
				mapHeights.resize(mapWidth*mapHeight);

				// Divide by 512 afterwards to get human readable size

				mapInfoFile << "Map Name: " << mapName << "\n";
				mapInfoFile << "Map Width: " << mapWidth << "\n";
				mapInfoFile << "Map Height: " << mapHeight << "\n";

				mapInfoFile << "\n";

				// Then include a csv equivalent grid of the heightmap/slopes

				// Write out the heightmap data
				for (int z = 0; z < mapHeight; ++z) {
					for (int x = 0; x < mapWidth; ++x) {
						mapHeights[z*mapWidth+x] = map->GetElevationAt(x*8, z*8); // Convert to full resolution
						mapHeightInfoFile << mapHeights[z*mapWidth+x] << ",";
					}
					mapHeightInfoFile << "\n";
				}
				mapHeightInfoFile << "\n";

				// Write out mass spot locations
				//std::vector<springai::AIFloat3> massSpots =  map->GetResourceMapSpotsPositions(callback->GetResourceByName("Metal"));
				//std::vector<springai::AIFloat3> hydroSpots =  map->GetResourceMapSpotsPositions(callback->GetResourceByName("Energy"));

				std::vector<short> metalMap;
				springai::Resource* metalResource = callback->GetResourceByName("Metal");
				springai::Resource* energyResource = callback->GetResourceByName("Energy");

				int mexCount = game->GetRulesParamFloat("mex_count", -1);

				mexCount = std::max(0, std::min(mexCount, 1000));  // safety measure
				std::vector<importantSpot> spots;
				spots.resize(mexCount);
				for (int i = 0; i < mexCount; ++i) {
					std::string param;
					spots[i].type = "Metal";
					param = IntToString(i + 1, "mex_metal%i");
					spots[i].value = game->GetRulesParamFloat(param.c_str(), 0.f); // This produces the value raw, not what the user sees for instance on my maps, divide by 1000 and round to nearest decimal
					spots[i].pos = springai::AIFloat3(0, 0, 0);
					param = IntToString(i + 1, "mex_x%i");
					spots[i].pos.x = game->GetRulesParamFloat(param.c_str(), 0.f);
					param = IntToString(i + 1, "mex_y%i");
					spots[i].pos.y = game->GetRulesParamFloat(param.c_str(), 0.f);
					param = IntToString(i + 1, "mex_z%i");
					spots[i].pos.z = game->GetRulesParamFloat(param.c_str(), 0.f);
					
					// spots[i].income = game->GetRulesParamFloat(param.c_str(), 0.f);
		//			CTerrainManager::SnapPosition(spots[i].position);  // IBuilderTask::SetBuildPos uses CTerrainManager::Pos2BuildPos(cdef, position)
				}

				for(int z = 0; z < spots.size(); z++){
					massInfoFile << spots[z].pos.x << "," << spots[z].pos.y << "," << spots[z].pos.z << "," << spots[z].value;
					massInfoFile << "\n";
				}
				massInfoFile << "\n";

				// Removed the hydro spot saving as currently the system has no reason to actually care for them
				// for(int z = 0; z < hydroSpots.size(); z++){
				// 	massInfoFile << hydroSpots[z].x << "," << hydroSpots[z].y << "," << hydroSpots[z].z << "," << hydroSpots[z].y;
				// 	massInfoFile << "\n";
				// }
				// massInfoFile << "\n";

				mapInfoFile.close();
				mapHeightInfoFile.close();
				massInfoFile.close();

				game->SendTextMessage(("/say Processed " + IntToString(spots.size()) + " mass spots").c_str(), 0);
				// IntToString(spawnPositions.size())).c_str()
			}

			connector = std::make_unique<TCPClient>("127.0.0.1", "25000");

			break;
		}
		case EVENT_UPDATE: {
			ProcessPauseWorkerState();

			const std::unique_ptr<springai::Game> game(callback->GetGame());
			std::string msgText;

			struct SUpdateEvent* evt = (struct SUpdateEvent*) data;
			int frame = evt->frame;
			if(frame%30 == 0){
				
				

				std::string msg = "";
				// Read in command from socket
				msg = connector->read_message();
				

				// Read in file information for moving the AI's units
				std::istringstream messageStream(msg);
				// std::string fileContent = LoadStreamIntoString(loadFileStream);
				
				if (!transfer){
					if(msg == "START\n"){
						transfer = true;
						game->SendTextMessage("/say Starting transfer", 0);
					}
					else{
						game->SendTextMessage("/say Waiting for start signal", 0);
						break;
					}
				}

				

				// Decode file into lines
				// Scan each line for a command
				// - if line contains a command, extract the arguments and execute it
				// - Only difference is for unit groups, if group/ungroup command, create new list of unit IDs

				// Old system, hunting specific commands
				// size_t movePos = fileContent.find("Move:");

				// Read every line, one by one
				std::string line;
				while(std::getline(messageStream, line)) {
					size_t commandPos = line.find("C:");
					if (commandPos == std::string::npos) {
						continue; // No command found, skip line
					}

					std::istringstream iss(line.substr(commandPos + 2)); // 2 is length of "C:"
					std::string command;
					iss >> command;

					if (command == "MU") { // Move
						int unitId;
						float x, z, y;
						std::string immediancy;
						bool shift;
						iss >> immediancy >> unitId >> x >> z >> y;
						if(immediancy == "Q")
							shift = 1;
						else
							shift = 0;
						
						springai::AIFloat3 targetPos(x, y, z);
						for(springai::Unit* unit : friendlyUnits){
							if(unit->GetUnitId() == unitId) {
								unit->MoveTo(targetPos, shift);
								msgText = std::string("/say Moving unit ") + IntToString(unitId)
									+ " to position " + targetPos.ToString();
								game->SendTextMessage(msgText.c_str(), 0);
							}
						}
					} 
					if (command == "BU") { // Build
						int unitId;
						float x, z, y;
						std::string immediacy;
						bool shift;
						std::string building;
						iss >> immediacy >> unitId >> x >> z >> y >> building;
						if(immediacy == "Q")
							shift = 1;
						else
							shift = 0;

						springai::AIFloat3 targetPos(x, y, z);
						for(springai::Unit* unit : friendlyUnits){
							if(unit->GetUnitId() == unitId) {
								std::unique_ptr<springai::UnitDef> def(callback->GetUnitDefByName(building.c_str()));
								if (def) {
									unit->Build(def.get(), targetPos, 0, shift);
								}
								msgText = std::string("/say Building unit ") + building + " with builder unit " + IntToString(unitId)
									+ " at position " + targetPos.ToString();
								game->SendTextMessage(msgText.c_str(), 0);
							}
						}
					}
					// add more commands here as needed
					if (command == "PAUSE") { // Pause command to allow external pauses for processing (Might be worth making the external more efficent)
						int pauseTime = 0;
						iss >> pauseTime;
						SetPauseForSeconds(pauseTime);
						game->SetPause(true, "AI needs to debug state");
					}
					if (command == "UNPAUSE") {
						game->SetPause(false, "AI is done debugging");
						aiPausedGame.store(false);
						unpauseRequested.store(false);
					}
				}
				
				if (game ->IsPaused()) {
					game->SendTextMessage("/say Currently paused, skipping turn actions", 0);
					break;
				}

				// Reconcile friendlyUnits with the engine each turn so nanoframes and any
				// units missed by events are always present (fixes serialization flags,
				// the nanoframe matcher, and projectOf staying fresh).
				{
					std::vector<springai::Unit*> fresh = callback->GetFriendlyUnits();
					for (springai::Unit* old : friendlyUnits) { delete old; }
					friendlyUnits = fresh;
				}

				// --- Poll builder command queues every 30 frames to keep tracking maps fresh ---
				// This catches: assisters joining, builders stopping/redirecting, etc.
				for (int builderId : myBuilders) {

					// msgText = std::string("/say Entered builder loop");
					// game->SendTextMessage(msgText.c_str(), 0);

					// Find the Unit* for this builder ID
					springai::Unit* builder = nullptr;
					for (springai::Unit* u : friendlyUnits) {
						if (u->GetUnitId() == builderId) { builder = u; break; }
					}
					if (builder == nullptr) continue;

					// msgText = std::string("/say Found builder unit for ID ") + IntToString(builderId);
					// game->SendTextMessage(msgText.c_str(), 0);

					// Get the front of the command queue
					std::vector<springai::Command*> cmds = builder->GetCurrentCommands();
					int currentNanoframeId = -1;

					msgText = std::string("/say Obtained commands for builder ID ") + IntToString(builderId) + ", num cmds: " + IntToString(cmds.size());
					game->SendTextMessage(msgText.c_str(), 0);

					for (springai::Command* cmd : cmds) {
						if (cmd == nullptr || cmd->GetId() >= 0) continue;

						// It's a build command. Find the nearest nanoframe to the build pos.
						const std::vector<float> params = cmd->GetParams();
						if (params.size() >= 3) {
							springai::AIFloat3 buildPos(params[0], params[1], params[2]);
							float bestDistSq = 128.0f * 128.0f;  // generous search radius

							for (springai::Unit* candidate : friendlyUnits) {
								if (candidate == nullptr || !candidate->IsBeingBuilt()) continue;
								springai::AIFloat3 cpos = candidate->GetPos();
								float dx = cpos.x - buildPos.x;
								float dz = cpos.z - buildPos.z;
								float distSq = dx*dx + dz*dz;
								if (distSq < bestDistSq) {
									bestDistSq = distSq;
									currentNanoframeId = candidate->GetUnitId();
								}
							}
						}
						break;  // only care about the front command
					}
					// delete any remaining commands not consumed above
					for (springai::Command* cmd : cmds) { delete cmd; }

					// msgText = std::string("/say Processed and cleaned commands for builder ID ") + IntToString(builderId) + ", current nanoframe ID: " + IntToString(currentNanoframeId);
					// game->SendTextMessage(msgText.c_str(), 0);

					// Update maps if the builder's target has changed
					int previousNanoframeId = -1;
					auto prevIt = projectOf.find(builderId);
					if (prevIt != projectOf.end())
						previousNanoframeId = prevIt->second;

					if (currentNanoframeId != previousNanoframeId) {
						// Remove from old nanoframe's builder set
						if (previousNanoframeId >= 0) {
							auto& bset = buildersOf[previousNanoframeId];
							bset.erase(builderId);
							if (bset.empty()) buildersOf.erase(previousNanoframeId);
						}
						// Add to new nanoframe's builder set
						if (currentNanoframeId >= 0) {
							buildersOf[currentNanoframeId].insert(builderId);
							projectOf[builderId] = currentNanoframeId;
						} else {
							projectOf.erase(builderId);
						}
					}
				}

				// Verify if anything has vision of the enemies last known position, if not, remove them from the known list 
				// This is to prevent the AI from making decisions based on outdated information, such as sending units to attack an enemy that has since moved away
				std::vector<fakeUnit> updatedKnownEnemies;
				const std::unique_ptr<springai::Map> map(callback->GetMap());
				const std::unique_ptr<springai::Mod> mod(callback->GetMod());
				const std::vector<int> losMap = map->GetLosMap();
				const std::vector<int> radarMap = map->GetRadarMap();
				const int mapWidth = map->GetWidth();
				const int mapHeight = map->GetHeight();
				const int losMip = mod->GetLosMipLevel();
				const int radarMip = mod->GetRadarMipLevel();
				const int losCellWorldSize = 8 * (1 << losMip);
				const int radarCellWorldSize = 8 * (1 << radarMip);
				const int losWidth = mapWidth >> losMip;
				const int losHeight = mapHeight >> losMip;
				const int radarWidth = mapWidth >> radarMip;
				const int radarHeight = mapHeight >> radarMip;

				for (const fakeUnit& unit : knownEnemyUnits) {
					const int losX = std::max(0, std::min(static_cast<int>(unit.pos.x) / losCellWorldSize, std::max(0, losWidth - 1)));
					const int losZ = std::max(0, std::min(static_cast<int>(unit.pos.z) / losCellWorldSize, std::max(0, losHeight - 1)));
					const int losIndex = (losZ * losWidth) + losX;

					const int radarX = std::max(0, std::min(static_cast<int>(unit.pos.x) / radarCellWorldSize, std::max(0, radarWidth - 1)));
					const int radarZ = std::max(0, std::min(static_cast<int>(unit.pos.z) / radarCellWorldSize, std::max(0, radarHeight - 1)));
					const int radarIndex = (radarZ * radarWidth) + radarX;

					const bool inVisualLos = (losIndex >= 0 && losIndex < static_cast<int>(losMap.size()) && losMap[losIndex] > 0);
					const bool inRadarCoverage = (radarIndex >= 0 && radarIndex < static_cast<int>(radarMap.size()) && radarMap[radarIndex] > 0);

					// Old behavior kept for reference:
					// if (!inVisualLos) {
					if (!(inVisualLos || inRadarCoverage)) {
						updatedKnownEnemies.push_back(unit);
					}
				}
				knownEnemyUnits = std::move(updatedKnownEnemies);

				// game->SendTextMessage("/say Ping Friendly", 0);
				// Send friendly units via socket
				// Contains  id, name, position(x y z), range, hp, speed
				// Enemies do not need speed, as they are not being commanded

				// Expected on the other side
				// ID, name, x, y, z, health, speed, isConstructing, activeBuildProgress

				msg = "FRIENDLY_UNITS\n";
				for (springai::Unit* unit : friendlyUnits) {
					auto pos = unit->GetPos();
					float range = unit->GetMaxRange();
					float speed = unit->GetMaxSpeed() * 30; // Convert from units/tick to units/second
					float hp = unit->GetHealth();
					// const std::pair<bool, float> buildState = resolveActiveBuildProgress(unit);
					int uid = unit->GetUnitId();
					bool isConstructing = false;
					float buildProgress = 0.0f;

					// Case 1: this unit IS a nanoframe being built by others
					if (unit->IsBeingBuilt()) {
						isConstructing = true;
						buildProgress = unit->GetBuildProgress();
					}
					// Case 2: this unit IS a builder actively constructing something
					else {
						auto projIt = projectOf.find(uid);
						if (projIt != projectOf.end()) {
							int nanoframeId = projIt->second;
							// Find the nanoframe unit and get its progress
							for (springai::Unit* candidate : friendlyUnits) {
								if (candidate->GetUnitId() == nanoframeId) {
									isConstructing = true;
									buildProgress = candidate->GetBuildProgress();
									break;
								}
							}
						}
					}

					std::string defName = safeUnitDefName(unit);
					msg += (std::to_string(unit->GetUnitId()) + " " + 
					defName + " " + 
					std::to_string(pos.x) + " " + 
					std::to_string(pos.y) + " " + 
					std::to_string(pos.z) + " " +
					std::to_string(hp) + " " + 
					std::to_string(speed) + " " +
					std::to_string(isConstructing ? 1 : 0) + " " +
					std::to_string(buildProgress) + "\n");
				}
				msg += "END\n";
				// connector->send_message(msg);
				
				// game->SendTextMessage("/say Ping Enemy", 0);
				// Send enemy units via socket
				msg += "ENEMY_UNITS\n";
				for (springai::Unit* unit : enemyUnits) {
					auto pos = unit->GetPos();
					float range = unit->GetMaxRange();
					float hp = unit->GetHealth();
					std::string defName = safeUnitDefName(unit);
					msg += std::to_string(unit->GetUnitId()) + " " + defName + " " + std::to_string(pos.x) + " " + std::to_string(pos.y) + " " + std::to_string(pos.z)  + " " + std::to_string(hp) + " " + std::to_string(0) + " " + std::to_string(0) + " " + std::to_string(0) + "\n";
				}
				msg += "END\n";
				//connector->send_message(msg);
				
				// game->SendTextMessage("/say Ping Known Enemy", 0);
				// Send known enemy units via socket
				msg += "KNOWN_ENEMY_UNITS\n";
				for (fakeUnit unit : knownEnemyUnits) {
					auto pos = unit.pos;
					float range = unit.range;
					float hp = unit.hp;
					msg += std::to_string(unit.id) + " " + unit.name + " " + std::to_string(pos.x) + " " + std::to_string(pos.y) + " " + std::to_string(pos.z) + " " + std::to_string(hp) + " " + std::to_string(0) + " " + std::to_string(0) + " " + std::to_string(0) + "\n";
				}
				msg += "END\n";
				//connector->send_message(msg);

				// Radar contacts are uncertain detections and should be consumed
				// separately from fully identified units.
				msg += "RADAR_ENEMY_UNITS\n";
				for (const fakeUnit& unit : radarEnemyUnits) {
					auto pos = unit.pos;
					msg += std::to_string(unit.id) + " " + unit.name + " " + std::to_string(pos.x) + " " + std::to_string(pos.y) + " " + std::to_string(pos.z) + " " + std::to_string(unit.hp) + " " + std::to_string(0) + " " + std::to_string(0) + " " + std::to_string(0) + "\n";
				}
				msg += "END\n";

				// Get how much metal/energy the team currently has
				msg += "RESOURCES "; 
				springai::Resource* metalResource = callback->GetResourceByName("Metal");
				springai::Resource* energyResource = callback->GetResourceByName("Energy");
				const int teamId = game->GetMyTeam();
				const int metalResourceId = metalResource->GetResourceId();
				const int energyResourceId = energyResource->GetResourceId();
				float currentMetal = game->GetTeamResourceCurrent(teamId, metalResourceId);
				float currentEnergy = game->GetTeamResourceCurrent(teamId, energyResourceId);
				msg += std::to_string(currentEnergy) + " " + std::to_string(currentMetal) + "\n";
				msg += "END\n";

				// Report units completed since the last turn message
				msg += "FINISHED\n";
				for (const auto& fin : finishedThisTurn) {
					msg += std::to_string(fin.first) + " " + fin.second + "\n";
				}
				msg += "END\n";
				finishedThisTurn.clear();

				msg += "TURN\n";
				// Trigger reward function
				connector->send_message(msg);
				game->SendTextMessage("/say Done Pinging", 0);
				

			}

			break;
		}
		case EVENT_ENEMY_ENTER_LOS: {
			struct SEnemyEnterLOSEvent* evt = (struct SEnemyEnterLOSEvent*) data;
			int unitId = evt->enemy;

			// Save information to vector
			std::vector<springai::Unit *> units = callback->GetEnemyUnits();
			const std::unique_ptr<springai::Game> game(callback->GetGame());
			try{
				for(springai::Unit* unit : units){
					if(unit->GetUnitId() == unitId){
						// auto itEK = std::find_if(knownEnemyUnits.begin(), knownEnemyUnits.end(), [unitId](const fakeUnit u){
						// 	return u.id == unitId;
						// });
						auto itE = std::find_if(enemyUnits.begin(), enemyUnits.end(), [unitId](const springai::Unit* u){
							return u->GetUnitId() == unitId;
						});
						// if(itEK == knownEnemyUnits.end()){
						// 	knownEnemyUnits.push_back(fakeUnit(unit->GetUnitId(), unit->GetDef()->GetName(), unit->GetMaxRange(), unit->GetPos(), unit->GetHealth()));
						// }
						// else{
						// 	itEK->pos = unit->GetPos();
						// 	itEK->hp = unit->GetHealth();
						// 	itEK->range = unit->GetMaxRange();
						// }

						// Promote the contact from radar-only to identified once LOS confirms it.
						UpsertFakeUnit(
							knownEnemyUnits,
							unit->GetUnitId(),
							safeUnitDefName(unit),
							unit->GetMaxRange(),
							unit->GetPos(),
							unit->GetHealth()
						);
						EraseFakeUnitById(radarEnemyUnits, unitId);
						if(itE == enemyUnits.end()){
							enemyUnits.push_back(unit);
						}
						break;
					}
				}

			}
			catch(...){
				game->SendTextMessage("Caused by ENEMY ENTER LOS", 0);
				exit(1);
			}

			break;
		}
		case EVENT_ENEMY_LEAVE_LOS: {
			struct SEnemyLeaveLOSEvent* evt = (struct SEnemyLeaveLOSEvent*) data;
			int unitId = evt->enemy;

			// NOTE: Do not demote the unit to knownEnemyUnits on LOS loss anymore.
			// The unit may still be visible on radar; demotion should occur when
			// the unit truly leaves radar (EVENT_ENEMY_LEAVE_RADAR).
			std::string msgText = std::string("/say LOS lost for Unit: ") + IntToString(unitId);
			const std::unique_ptr<springai::Game> game(callback->GetGame());
			game->SendTextMessage(msgText.c_str(), 0);

			// Original demotion-on-LOS code preserved (commented) for reference:
			// try{
			//     for(springai::Unit* unit : enemyUnits){
			//         if(unit->GetUnitId() == unitId){
			//             // upsert into knownEnemyUnits ...
			//             break;
			//         }
			//     }
			// }
			// catch(...){
			//     game->SendTextMessage("Caused by ENEMY LEAVE LOS", 0);
			//     exit(1);
			// }

			break;
		}
		case EVENT_ENEMY_DESTROYED: {
			struct SEnemyDestroyedEvent* evt = (struct SEnemyDestroyedEvent*) data;
			int unitId = evt->enemy;

			// knownEnemyUnits.erase(
			// 	std::remove_if(
			// 		knownEnemyUnits.begin(),
			// 		knownEnemyUnits.end(),
			// 		[unitId](fakeUnit unit) {
			// 			return unit.id == unitId;
			// 		}
			// 	),
			// 	knownEnemyUnits.end()
			// );
			EraseFakeUnitById(knownEnemyUnits, unitId);
			EraseFakeUnitById(radarEnemyUnits, unitId);
			enemyUnits.erase(
				std::remove_if(
					enemyUnits.begin(),
					enemyUnits.end(),
					[unitId](springai::Unit* unit) {
						return unit->GetUnitId() == unitId;
					}
				),
				enemyUnits.end()
			);

			break;
		}
		case EVENT_ENEMY_ENTER_RADAR: {
			struct SEnemyEnterRadarEvent* evt = (struct SEnemyEnterRadarEvent*) data;
			int unitId = evt->enemy;
			const std::vector<springai::Unit*> units = callback->GetEnemyUnitsInRadarAndLos();

			// Similar to ENEMY_ENTER_LOS but for radar detection, might want to track separately for different decision making processes
			// Radar can report a contact before identity is known, so we keep
			// a generic placeholder unless LOS already identified this unit.
			auto itEnemy = std::find_if(enemyUnits.begin(), enemyUnits.end(), [unitId](const springai::Unit* u){
				return u->GetUnitId() == unitId;
			});
			if (itEnemy != enemyUnits.end()) {
				break;
			}

			springai::AIFloat3 radarPos(0, 0, 0);
			for (springai::Unit* unit : units) {
				if (unit->GetUnitId() == unitId) {
					radarPos = unit->GetPos();
					break;
				}
			}

			auto itKnown = std::find_if(knownEnemyUnits.begin(), knownEnemyUnits.end(), [unitId](const fakeUnit& u){
				return u.id == unitId;
			});
			if (itKnown != knownEnemyUnits.end()) {
				UpsertFakeUnit(radarEnemyUnits, unitId, itKnown->name, itKnown->range, radarPos, itKnown->hp);
			} else {
				UpsertFakeUnit(radarEnemyUnits, unitId, RADAR_UNKNOWN_NAME, 0, radarPos, -1.0f);
			}

			break;
		}
		case EVENT_ENEMY_LEAVE_RADAR: {
			struct SEnemyLeaveRadarEvent* evt = (struct SEnemyLeaveRadarEvent*) data;
			int unitId = evt->enemy;

			// When a unit leaves radar we demote it to the known/fogged list
			// (last known position/name/hp), because it is no longer actively
			// tracked by any of our sensors.
			const std::unique_ptr<springai::Game> game(callback->GetGame());

			// Save radar-only placeholder data before erasing it, so contacts that
			// were seen only on radar can persist in knownEnemyUnits until LOS
			// later passes over and clears the last known position.
			fakeUnit radarSnapshot(unitId, RADAR_UNKNOWN_NAME, 0, springai::AIFloat3(0, 0, 0), -1.0f);
			bool hasRadarSnapshot = false;
			auto itRadar = std::find_if(radarEnemyUnits.begin(), radarEnemyUnits.end(), [unitId](const fakeUnit& u){
				return u.id == unitId;
			});
			if (itRadar != radarEnemyUnits.end()) {
				radarSnapshot = *itRadar;
				hasRadarSnapshot = true;
			}

			// Original behavior preserved for reference:
			// EraseFakeUnitById(radarEnemyUnits, unitId);
			EraseFakeUnitById(radarEnemyUnits, unitId);

			// If it's still present as a live enemy unit, copy to known list
			bool foundLiveEnemyUnit = false;
			try {
				for (springai::Unit* unit : enemyUnits) {
					if (unit->GetUnitId() == unitId) {
						foundLiveEnemyUnit = true;
						auto itEK = std::find_if(knownEnemyUnits.begin(), knownEnemyUnits.end(), [unitId](const fakeUnit& u){
							return u.id == unitId;
						});
						if (itEK == knownEnemyUnits.end()) {
							knownEnemyUnits.push_back(fakeUnit(unit->GetUnitId(), safeUnitDefName(unit), unit->GetMaxRange(), unit->GetPos(), unit->GetHealth()));
						} else {
							itEK->pos = unit->GetPos();
							itEK->hp = unit->GetHealth();
							itEK->range = unit->GetMaxRange();
						}
						break;
					}
				}
			}
			catch(...) {
				game->SendTextMessage("Caused by ENEMY LEAVE RADAR", 0);
			}

			// If this was radar-only (never in enemyUnits), keep its last known
			// radar position in knownEnemyUnits until LOS later proves the area clear.
			if (!foundLiveEnemyUnit && hasRadarSnapshot) {
				UpsertFakeUnit(
					knownEnemyUnits,
					radarSnapshot.id,
					radarSnapshot.name,
					radarSnapshot.range,
					radarSnapshot.pos,
					radarSnapshot.hp
				);
			}

			// Finally remove from live enemy list (no longer visible)
			try {
				enemyUnits.erase(
					std::remove_if(
						enemyUnits.begin(),
						enemyUnits.end(),
						[unitId](springai::Unit* unit) {
							return unit->GetUnitId() == unitId;
						}
					),
					enemyUnits.end()
				);
			}
			catch(...) {
				game->SendTextMessage("Caused by EVENT LEAVE RADAR", 0);
			}

			break;
		}
		case EVENT_RELEASE: {
			const struct SReleaseEvent* evt = (const struct SReleaseEvent*)data;
			const std::unique_ptr<springai::Game> game(callback->GetGame());

			std::string reason;
			switch (evt->reason) {
				case 1: reason = "GAME_ENDED"; break;
				case 2: reason = "TEAM_DIED"; break;
				case 3: reason = "AI_KILLED"; break;
				default: reason = "GAMESTOP"; break;
			}

			game->SendTextMessage(("/say AI releasing: " + reason).c_str(), 0);
			connector->send_message(reason);
			StopPauseWorker();

			// End match


			break;  // note: you're currently missing this break before default
		}
		case EVENT_LUA_MESSAGE: {
			const struct SLuaMessageEvent* evt = (const struct SLuaMessageEvent*)data;
			if (std::string(evt->inData) == "GAMEOVER") {
				connector->send_message("GAME_ENDED");
				const std::unique_ptr<springai::Game> game(callback->GetGame());
				game->SendTextMessage("/say AI releasing: GAME_ENDED", 0);
				StopPauseWorker();
				// cleanup, etc.
			}
			break;
		}
		default: {
			break;
		}
	}

	// signal: everything went OK
	return 0;
}


// Template for exporting the map information
// Grab height and export it as a csv, don't need to do this every frame, probably either during a big event or every 30 seconds
// Thankfully water does not need to be exported differently, its height is fixed at a given height, anything below that value can be assumed water

// Next is a similar CSV bound based on the enemy ranges provided by the enemy units in LOS
// Might be possible to combine it with the known enemies but have to be careful wtih doubleing up statistics
// This can be used to help with pathfinding and base placement

// Then, terrain type can be exported as well
// Within bar this falls down to affecting ground based vehicles, exception being hovercraft

// Finally, resource locations and amounts can be exported as well for base placement and expansion decisions