local objectname= "ad0_senegal_6" 
local featureDef	=	{
	name			= "ad0_senegal_6",
	world				="All Worlds",
	description				="Palm Tree",
	category				="Vegetation",
	object				="ad0_senegal_6.s3o",
	footprintx				=1,
	footprintz				=1,
	height				=30,
	blocking				=true,
	upright				=true,
	hitdensity				=0,
	energy				=250,
	metal				=0,
	mass				=20,
	flammable				=true,
	reclaimable				=true,
	autoreclaimable				=true,
	featurereclamate				="smudge01",
	seqnamereclamate				="tree1reclamate",
	customparams = {
		model_author = "ad0",
		normalmaps = "yes",
		normaltex = "unittextures/ad0senegal_normal.tga",
		treeshader = "yes",
	},
} 
return lowerkeys({[objectname] = featureDef}) 
