/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

#include "CppTestAI.h"


#include "ExternalAI/Interface/AISEvents.h"
#include "ExternalAI/Interface/AISCommands.h"

// generated by the C++ Wrapper scripts
#include "OOAICallback.h"
#include "Unit.h"
#include "UnitDef.h"
#include "MoveData.h"
#include "DataDirs.h"
#include "Game.h"
#include "Map.h"
#include "Cheats.h"
#include "Command.h"

#include <string>
#include <memory>
#include <fstream>
#include <cstring>

cpptestai::CCppTestAI::CCppTestAI(springai::OOAICallback* callback):
		callback(callback),
		skirmishAIId(callback != NULL ? callback->GetSkirmishAIId() : -1)
		{}

cpptestai::CCppTestAI::~CCppTestAI() {}

std::vector<springai::Unit*> friendlyUnits = std::vector<springai::Unit*>();
std::vector<springai::AIFloat3> massSpots = std::vector<springai::AIFloat3>();
bool massSpotsInitialized = false;

bool initialBuilding = false;
bool faction = false;
int dangerSpawn = 10;

static inline std::string IntToString(int i, const std::string& format = "%i")
{
	char buf[64];
	SNPRINTF(buf, sizeof(buf), format.c_str(), i);
	return std::string(buf);
}

static inline std::string FloatToString(float f, const std::string& format = "%.3f")
{
	char buf[64];
	SNPRINTF(buf, sizeof(buf), format.c_str(), f);
	return std::string(buf);
}

int cpptestai::CCppTestAI::HandleEvent(int topic, const void* data) {

	switch (topic) {
		case EVENT_UPDATE: {
			const std::unique_ptr<springai::Game> game(callback->GetGame());
			std::unique_ptr<springai::Cheats> cheats(callback->GetCheats());
			cheats->SetEnabled(true);
			const std::unique_ptr<springai::Map> map(callback->GetMap());
			struct SUpdateEvent* evt = (struct SUpdateEvent*) data;
			int frame = evt->frame;
			
			
			if(frame%60 == 0){
				
				auto* metalResource = callback->GetResourceByName("Metal");
				std::vector<springai::Unit*> Units = callback->GetFriendlyUnits();

				game->SendTextMessage("/say Update", 0);

				if(!massSpotsInitialized || massSpots.empty()){
					massSpots = map->GetResourceMapSpotsPositions(metalResource);
					massSpotsInitialized = !massSpots.empty();
					game->SendTextMessage("/say Mass spots initialized", 0);
				}
				else if(Units.size() == 1){
					// Spawn in laser unit to control
					springai::AIFloat3 spawnPos = massSpots[0];
					spawnPos.y = map->GetElevationAt(spawnPos.x, spawnPos.z);
					// Randomly choose between a few laser units
					// Pull number between 1 and 100
					// 1-20 -> mammoth
					// 21-80 -> corgator
					// 81-100 -> centurion
					int choice = rand() % 100 + 1;
					springai::UnitDef* spawnDef;
					if (choice <= 10) {
						spawnDef = callback->GetUnitDefByName("armcroc");
					} else if (choice <= 70) {
						spawnDef = callback->GetUnitDefByName("corthud");
					} else {
						spawnDef = callback->GetUnitDefByName("armstump");
					}
					dangerSpawn += 10;
					const int spawnedUnitId = cheats->GiveMeUnit(spawnDef, spawnPos);
					game->SendTextMessage(("/say Spawned unit with ID: " + IntToString(spawnedUnitId)).c_str(), 0);
				}
				else{
					try{
						for(springai::Unit* unit : Units){
							const char* unitDefName = unit->GetDef()->GetName();
							game->SendTextMessage(("/say Processing unit with ID: " + IntToString(unit->GetUnitId()) + " and name: " + (unitDefName != nullptr ? unitDefName : "<null>")).c_str(), 0);
							if(unitDefName != nullptr && (std::strcmp(unitDefName, "armcom") == 0 || std::strcmp(unitDefName, "corcom") == 0)){
								continue;
							}
							if (massSpots.empty()) {
								game->SendTextMessage("/say Spot pool exhausted for this cycle", 0);
								break;
							}

							// check to see if unit has a command currently
							std::vector<springai::Command*> commands = unit->GetCurrentCommands();
							
							// print commands for debugging
							std::string commandMsg = "/say Current commands for unit " + IntToString(unit->GetUnitId()) + ": ";
							for(springai::Command* cmd : commands){
								if (cmd != nullptr) {
									commandMsg += IntToString(cmd->GetId()) + " ";
								}
							}
							game->SendTextMessage(commandMsg.c_str(), 0);

							if(commands.size() > 0){
								continue;
							}
							// send them to the nearest mass spot
							size_t closestIndex = 0;
							springai::AIFloat3 closestSpot = massSpots[closestIndex];
							std::string posMsg = "/say Choosing spot with initial choice of: " + closestSpot.ToString();
							game->SendTextMessage(posMsg.c_str(), 0);

							float closestDist = (unit->GetPos() - massSpots[closestIndex]).SqLength();
							try{
								for(size_t i = 0; i < massSpots.size(); ++i){
									const springai::AIFloat3& spot = massSpots[i];
									float dist = (unit->GetPos() - spot).SqLength();
									if(dist < closestDist){ // check if spot is taken
										closestDist = dist;
										closestIndex = i;
										closestSpot = spot;
									}
								}

								closestSpot.y = map->GetElevationAt(closestSpot.x, closestSpot.z);

								unit->MoveTo(closestSpot);

								massSpots.erase(massSpots.begin() + closestIndex);
							}
							catch(...){
								game->SendTextMessage("/say Error occurred while moving unit", 0);
							}

							// game->SendTextMessage("/say Spot chosen and position:", 0);
							posMsg = "/say Spot chosen: " + closestSpot.ToString();
							game->SendTextMessage(posMsg.c_str(), 0);

							game->SendTextMessage("/say Spot chosen", 0);
						}
						
					}
					catch(...){
						game->SendTextMessage("/say Error occurred in UPDATE", 0);
					}
				}
			}

		}
		default: {
			break;
		}
	}

	// signal: everything went OK
	return 0;
}
