/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

#include "CppTestAI.h"


#include "ExternalAI/Interface/AISEvents.h"
#include "ExternalAI/Interface/AISCommands.h"

// generated by the C++ Wrapper scripts
#include "OOAICallback.h"
#include "Unit.h"
#include "UnitDef.h"
#include "MoveData.h"
#include "DataDirs.h"
#include "Game.h"
#include "Map.h"
#include "Cheats.h"
#include "Command.h"
#include "WrappGroup.h"
#include "WrappUnit.h"
#include "AISCommands.h"

#include <string>
#include <memory>
#include <fstream>
#include <cstring>

cpptestai::CCppTestAI::CCppTestAI(springai::OOAICallback* callback):
		callback(callback),
		skirmishAIId(callback != NULL ? callback->GetSkirmishAIId() : -1)
		{}

cpptestai::CCppTestAI::~CCppTestAI() {}

std::vector<springai::Unit*> friendlyUnits = std::vector<springai::Unit*>();
std::vector<springai::AIFloat3> massSpots = std::vector<springai::AIFloat3>();
bool massSpotsInitialized = false;

bool initialBuilding = false;
bool faction = false;
int activeGroupId = -1;
springai::Group* activeGroup = nullptr;
std::vector<int> trackedGroupUnitIds = std::vector<int>();

static inline bool ContainsUnitId(const std::vector<int>& ids, int unitId)
{
	for (int id : ids) {
		if (id == unitId) {
			return true;
		}
	}
	return false;
}




static inline std::string IntToString(int i, const std::string& format = "%i")
{
	char buf[64];
	SNPRINTF(buf, sizeof(buf), format.c_str(), i);
	return std::string(buf);
}

static inline std::string FloatToString(float f, const std::string& format = "%.3f")
{
	char buf[64];
	SNPRINTF(buf, sizeof(buf), format.c_str(), f);
	return std::string(buf);
}

int cpptestai::CCppTestAI::HandleEvent(int topic, const void* data) {

	switch (topic) {
		case EVENT_UPDATE: {
			const std::unique_ptr<springai::Game> game(callback->GetGame());
			std::unique_ptr<springai::Cheats> cheats(callback->GetCheats());
			cheats->SetEnabled(true);
			const std::unique_ptr<springai::Map> map(callback->GetMap());
			struct SUpdateEvent* evt = (struct SUpdateEvent*) data;
			int frame = evt->frame;
			
			
			if(frame%60 == 0){
				
				auto* metalResource = callback->GetResourceByName("Metal");
				std::vector<springai::Unit*> Units = callback->GetFriendlyUnits();

				game->SendTextMessage("/say Update", 0);

				if(!massSpotsInitialized || massSpots.empty()){
					massSpots = map->GetResourceMapSpotsPositions(metalResource);
					massSpotsInitialized = !massSpots.empty();
					game->SendTextMessage("/say Mass spots initialized", 0);
				}
				else if(Units.size() == 1){
					// Spawn in laser unit to control
					springai::AIFloat3 spawnPos = massSpots[0];
					spawnPos.y = map->GetElevationAt(spawnPos.x, spawnPos.z);

					if (activeGroupId < 0) {
						springai::Group* groupTemplate = springai::WrappGroup::GetInstance(skirmishAIId, 0);
						if (groupTemplate == nullptr) {
							game->SendTextMessage("/say Failed to allocate group template", 0);
							return 0;
						}

						activeGroupId = groupTemplate->Create();
						if (activeGroupId < 0) {
							game->SendTextMessage("/say Failed to create group", 0);
							return 0;
						}

						activeGroup = springai::WrappGroup::GetInstance(skirmishAIId, activeGroupId);
					}

					const int unitChoices[3][3] = {
						{10, 70, 100},
						{10, 70, 100},
						{10, 70, 100},
					};
					const char* unitNames[3][3] = {
						{"armcroc", "corthud", "armstump"},
						{"corcan", "corgator", "armwar"},
						{"armjanus", "armrock", "armsam"},
					};

					for (int i = 0; i < 3; ++i) {
						int choice = rand() % 100 + 1;
						const char* unitName = nullptr;
						if (choice <= unitChoices[i][0]) {
							unitName = unitNames[i][0];
						} else if (choice <= unitChoices[i][1]) {
							unitName = unitNames[i][1];
						} else {
							unitName = unitNames[i][2];
						}

						springai::UnitDef* spawnDef = callback->GetUnitDefByName(unitName);
						int spawnedUnitId = cheats->GiveMeUnit(spawnDef, spawnPos);
						if (!ContainsUnitId(trackedGroupUnitIds, spawnedUnitId)) {
							trackedGroupUnitIds.push_back(spawnedUnitId);
						}

						springai::Unit* spawnedUnit = springai::WrappUnit::GetInstance(skirmishAIId, spawnedUnitId);
						if (spawnedUnit != nullptr && activeGroup != nullptr) {
							spawnedUnit->AddToGroup(activeGroup);
						}
					}

					game->SendTextMessage("/say Spawned units", 0);
				}
				else{
					try{
						std::vector<springai::Unit*> groupUnits;
						std::vector<int> aliveTrackedIds;

						for (int trackedId : trackedGroupUnitIds) {
							for (springai::Unit* unit : Units) {
								if (unit != nullptr && unit->GetUnitId() == trackedId) {
									aliveTrackedIds.push_back(trackedId);
									break;
								}
							}
						}
						trackedGroupUnitIds = aliveTrackedIds;

						for(springai::Unit* unit : Units){
							if (unit != nullptr && ContainsUnitId(trackedGroupUnitIds, unit->GetUnitId())) {
								groupUnits.push_back(unit);
							}
						}

						if (trackedGroupUnitIds.size() < 3 && activeGroup != nullptr && !massSpots.empty()) {
							springai::AIFloat3 spawnPos = massSpots[0];
							spawnPos.y = map->GetElevationAt(spawnPos.x, spawnPos.z);

							int choice = rand() % 100 + 1;
							const char* unitName = (choice <= 10) ? "armcroc" : (choice <= 70) ? "corthud" : "armstump";
							springai::UnitDef* spawnDef = callback->GetUnitDefByName(unitName);
							int spawnedUnitId = cheats->GiveMeUnit(spawnDef, spawnPos);
							if (!ContainsUnitId(trackedGroupUnitIds, spawnedUnitId)) {
								trackedGroupUnitIds.push_back(spawnedUnitId);
							}

							springai::Unit* spawnedUnit = springai::WrappUnit::GetInstance(skirmishAIId, spawnedUnitId);
							if (spawnedUnit != nullptr) {
								spawnedUnit->AddToGroup(activeGroup);
							}

							game->SendTextMessage("/say Spawned new unit", 0);
						}

						const bool hasFullGroup = (trackedGroupUnitIds.size() == 3 && groupUnits.size() == 3);
						bool allIdle = hasFullGroup;
						for (springai::Unit* unit : groupUnits) {
							std::vector<springai::Command*> commands = unit->GetCurrentCommands();
							if (!commands.empty()) {
								allIdle = false;
								break;
							}
						}

						if (allIdle && !groupUnits.empty() && !massSpots.empty() && activeGroup != nullptr) {
							size_t closestIndex = 0;
							springai::AIFloat3 closestSpot = massSpots[closestIndex];
							std::string posMsg = "/say Choosing spot with initial choice of: " + closestSpot.ToString();
							game->SendTextMessage(posMsg.c_str(), 0);

							float closestDist = (groupUnits[0]->GetPos() - massSpots[closestIndex]).SqLength();
							try{
								for(size_t i = 0; i < massSpots.size(); ++i){
									const springai::AIFloat3& spot = massSpots[i];
									float dist = (groupUnits[0]->GetPos() - spot).SqLength();
									if(dist < closestDist){
										closestDist = dist;
										closestIndex = i;
										closestSpot = spot;
									}
								}

								closestSpot.y = map->GetElevationAt(closestSpot.x, closestSpot.z);
								massSpots.erase(massSpots.begin() + closestIndex);
							}
							catch(...){
								game->SendTextMessage("/say Error while choosing spot", 0);
							}

							for (springai::Unit* unit : groupUnits) {
								const char* unitDefName = unit->GetDef()->GetName();
								game->SendTextMessage(("/say Processing unit with ID: " + IntToString(unit->GetUnitId()) + " and name: " + (unitDefName != nullptr ? unitDefName : "<null>")).c_str(), 0);
								unit->MoveTo(closestSpot);
							}

							posMsg = "/say Spot chosen: " + closestSpot.ToString();
							game->SendTextMessage(posMsg.c_str(), 0);
							game->SendTextMessage("/say Spot chosen", 0);
						}

					}
					catch(...){
						game->SendTextMessage("/say Error occurred in UPDATE", 0);
					}
				}
			}

		}
		default: {
			break;
		}
	}

	// signal: everything went OK
	return 0;
}
