/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

#include "CppTestAI.h"


#include "ExternalAI/Interface/AISEvents.h"
#include "ExternalAI/Interface/AISCommands.h"

// generated by the C++ Wrapper scripts
#include "OOAICallback.h"
#include "Unit.h"
#include "UnitDef.h"
#include "MoveData.h"
#include "DataDirs.h"
#include "Game.h"
#include "Map.h"

#include <string>
#include <memory>
#include <fstream>
#include <string>

// for vector removal
#include <algorithm>
#include "Command.h"

cpptestai::CCppTestAI::CCppTestAI(springai::OOAICallback* callback):
		callback(callback),
		skirmishAIId(callback != NULL ? callback->GetSkirmishAIId() : -1)
		{}

cpptestai::CCppTestAI::~CCppTestAI() {}

// make the masspoint tracker

//std::vector<springai::Unit*> friendlyUnits = std::vector<springai::Unit*>();
std::vector<springai::AIFloat3> massSpots = std::vector<springai::AIFloat3>();
bool massSpotsInitialized = false;

static inline std::string IntToString(int i, const std::string& format = "%i")
{
	char buf[64];
	SNPRINTF(buf, sizeof(buf), format.c_str(), i);
	return std::string(buf);
}

static inline std::string FloatToString(float f, const std::string& format = "%.3f")
{
	char buf[64];
	SNPRINTF(buf, sizeof(buf), format.c_str(), f);
	return std::string(buf);
}

int cpptestai::CCppTestAI::HandleEvent(int topic, const void* data) {

	switch (topic) {
		// case EVENT_UNIT_CREATED: {
		// 	struct SUnitCreatedEvent* evt = (struct SUnitCreatedEvent*) data;
		// 	int unitId = evt->unit;
		// 	const std::unique_ptr<springai::Game> game(callback->GetGame());
		// 	game->SendTextMessage("/say Is anything running here or is it dying immediately?", 0);
		// 	std::vector<springai::Unit*> Units = callback->GetFriendlyUnits();

		// 	game->SendTextMessage("/say Is anything running here or is it dying immediately?", 0);

		// 	const std::unique_ptr<springai::Map> map(callback->GetMap());

		// 	massSpots =  map->GetResourceMapSpotsPositions(callback->GetResourceByName("Metal"));
		// 	massSpotTaken.resize(massSpots.size(), false);
		// 	massSpotsInitialized = true;
		// 	try{
		// 		for(springai::Unit* unit : Units){
		// 			if(unit->GetUnitId() == unitId){
		// 				// send them to the nearest mass spot
		// 				float closestDist = (unit->GetPos() - massSpots[0]).SqLength();
		// 				springai::AIFloat3 closestSpot = massSpots[0];
		// 				for(springai::AIFloat3 spot : massSpots){
		// 					float dist = (unit->GetPos() - spot).SqLength();
		// 					if(dist < closestDist){
		// 						closestDist = dist;
		// 						closestSpot = spot;
		// 					}
		// 				}

		// 				game->SendTextMessage("/say Choosing spot", 0);

		// 				unit->MoveTo(closestSpot); // Convert to full resolution

		// 				game->SendTextMessage("/say Spot chosen and position:", 0);
		// 				std::string posMsg = closestSpot.ToString();
		// 				game->SendTextMessage(posMsg.c_str(), 0);

		// 				game->SendTextMessage("/say Moving to spot", 0);
						
		// 				// mark off mass spot as taken
		// 				auto it = std::find(massSpots.begin(), massSpots.end(), closestSpot);
		// 				if(it != massSpots.end()){
		// 					massSpotTaken[std::distance(massSpots.begin(), it)] = true;
		// 				}

		// 				game->SendTextMessage("/say Spot chosen", 0);
		// 			}
		// 		}
		// 	}
		// 	catch(...){
		// 		game->SendTextMessage("/say Error occurred in UNIT_FINISHED", 0);
		// 	}
		// 	break;
		// }
		// case EVENT_UNIT_IDLE: {
		// 	const std::unique_ptr<springai::Game> game(callback->GetGame());
		// 	struct SUnitIdleEvent* evt = (struct SUnitIdleEvent*) data;
		// 	int unitId = evt->unit;

		// 	// Find the next closest mass spot for the given unit
		// 	std::vector<springai::Unit*> Units = callback->GetFriendlyUnits();

		// 	try{
		// 		for(springai::Unit* unit : Units){
		// 			if(unit->GetUnitId() == unitId && massSpotsInitialized){
		// 				// send them to the nearest mass spot
		// 				float closestDist = (unit->GetPos() - massSpots[0]).SqLength();
		// 				springai::AIFloat3 closestSpot = massSpots[0];
		// 				for(springai::AIFloat3 spot : massSpots){
		// 					float dist = (unit->GetPos() - spot).SqLength();
		// 					if(dist < closestDist){
		// 						closestDist = dist;
		// 						closestSpot = spot;
		// 					}
		// 				}

		// 				game->SendTextMessage("/say Choosing spot", 0);

		// 				unit->MoveTo(closestSpot); // Convert to full resolution

		// 				game->SendTextMessage("/say Moving to spot", 0);

		// 				// mark off mass spot as taken
		// 				auto it = std::find(massSpots.begin(), massSpots.end(), closestSpot);
		// 				if(it != massSpots.end()){
		// 					massSpotTaken[std::distance(massSpots.begin(), it)] = true;
		// 				}

		// 				game->SendTextMessage("/say Spot chosen and position:", 0);
		// 				std::string posMsg = closestSpot.ToString();
		// 				game->SendTextMessage(posMsg.c_str(), 0);
		// 			}
		// 		}
		// 	}
		// 	catch(...){
		// 		game->SendTextMessage("/say Error occurred in UNIT_IDLE", 0);
		// 	}

		// 	game->SendTextMessage("/say Idle Processed", 0);

		// 	if(massSpotsInitialized){

		// 		// Check to see if all mass spots are taken
		// 		// if so, reset the list
		// 		bool allTaken = true;
		// 		for(bool taken : massSpotTaken){
		// 			if(!taken){
		// 				allTaken = false;
		// 				break;
		// 			}
		// 		}

		// 		game->SendTextMessage("/say Resetting mass spots", 0);

		// 		if(allTaken){
		// 			for(int i = 0; i < massSpotTaken.size(); i++){
		// 				massSpotTaken[i] = false;
		// 			}
		// 		}

		// 		game->SendTextMessage("/say Mass spots reset", 0);
		// 	}
		// 	break;
		// }
		case EVENT_UPDATE: {
			const std::unique_ptr<springai::Game> game(callback->GetGame());
			if (game == nullptr) {
				break;
			}

			struct SUpdateEvent* evt = (struct SUpdateEvent*) data;
			int frame = evt->frame;

			if(frame%60 == 0){
				const std::unique_ptr<springai::Map> map(callback->GetMap());
				if (map == nullptr) {
					game->SendTextMessage("/say Map callback was null", 0);
					break;
				}

				auto* metalResource = callback->GetResourceByName("Metal");
				if (metalResource == nullptr) {
					game->SendTextMessage("/say Metal resource lookup failed", 0);
					break;
				}

				std::vector<springai::Unit*> Units = callback->GetFriendlyUnits();

				game->SendTextMessage("/say Update", 0);

				if(!massSpotsInitialized || massSpots.empty()){
					massSpots = map->GetResourceMapSpotsPositions(metalResource);
					massSpotsInitialized = !massSpots.empty();
					if (massSpots.empty()) {
						game->SendTextMessage("/say No metal spots available this cycle", 0);
					}
				}
				else{
					try{
						for(springai::Unit* unit : Units){
							if (unit == nullptr) {
								continue;
							}
							if (massSpots.empty()) {
								game->SendTextMessage("/say Spot pool exhausted for this cycle", 0);
								break;
							}

							// check to see if unit has a command currently
							std::vector<springai::Command*> commands = unit->GetCurrentCommands();
							
							// print commands for debugging
							std::string commandMsg = "/say Current commands for unit " + IntToString(unit->GetUnitId()) + ": ";
							for(springai::Command* cmd : commands){
								if (cmd != nullptr) {
									commandMsg += IntToString(cmd->GetId()) + " ";
								}
							}
							game->SendTextMessage(commandMsg.c_str(), 0);

							if(commands.size() > 0){
								continue;
							}
							// send them to the nearest mass spot
							size_t closestIndex = 0;
							springai::AIFloat3 closestSpot = massSpots[closestIndex];
							std::string posMsg = "/say Choosing spot with initial choice of: " + closestSpot.ToString();
							game->SendTextMessage(posMsg.c_str(), 0);

							float closestDist = (unit->GetPos() - massSpots[closestIndex]).SqLength();
							try{
								for(size_t i = 0; i < massSpots.size(); ++i){
									const springai::AIFloat3& spot = massSpots[i];
									float dist = (unit->GetPos() - spot).SqLength();
									if(dist < closestDist){ // check if spot is taken
										closestDist = dist;
										closestIndex = i;
										closestSpot = spot;
									}
								}

								closestSpot.y = map->GetElevationAt(closestSpot.x, closestSpot.z);

								unit->MoveTo(closestSpot);

								massSpots.erase(massSpots.begin() + closestIndex);
							}
							catch(...){
								game->SendTextMessage("/say Error occurred while moving unit", 0);
							}

							// game->SendTextMessage("/say Spot chosen and position:", 0);
							posMsg = "/say Spot chosen: " + closestSpot.ToString();
							game->SendTextMessage(posMsg.c_str(), 0);

							game->SendTextMessage("/say Spot chosen", 0);
						}
						
					}
					catch(...){
						game->SendTextMessage("/say Error occurred in UPDATE", 0);
					}
				}
			}
			break;
		}
		default: {
			break;
		}
	}

	// signal: everything went OK
	return 0;
}
